""""
XLS data reader unit for the MICS project
(c) Valeriy Chepelev
LGPL licensing
"""


def read_data(filename: str) -> dict:
    """Read assotiation data from a file,
    return dictionary DA-name: signal name"""
    return _test_data


_test_data = {"LD0/AB_TVTR1/Beh/q": "",
              "LD0/AB_TVTR1/Beh/stVal": "850_ALL_BEH",
              "LD0/AB_TVTR1/EEHealth/q": "",
              "LD0/AB_TVTR1/EEHealth/stVal": "850_TVTR1_HEAL",
              "LD0/A_TCTR1/Beh/q": "",
              "LD0/A_TCTR1/Beh/stVal": "850_ALL_BEH",
              "LD0/A_TCTR1/EEHealth/q": "",
              "LD0/A_TCTR1/EEHealth/stVal": "850_TCTR1_HEAL",
              "LD0/BC_TVTR1/Beh/q": "",
              "LD0/BC_TVTR1/Beh/stVal": "850_ALL_BEH",
              "LD0/BC_TVTR1/EEHealth/q": "",
              "LD0/BC_TVTR1/EEHealth/stVal": "850_TVTR1_HEAL",
              "LD0/B_TCTR1/Beh/q": "",
              "LD0/B_TCTR1/Beh/stVal": "850_ALL_BEH",
              "LD0/B_TCTR1/EEHealth/q": "",
              "LD0/B_TCTR1/EEHealth/stVal": "850_TCTR1_HEAL",
              "LD0/CALH1/Beh/q": "",
              "LD0/CALH1/Beh/stVal": "850_ALL_BEH",
              "LD0/CALH1/GrAlm/q": "",
              "LD0/CALH1/GrAlm/stVal": "Реле Авар.откл.",
              "LD0/CALH1/GrWrn/q": "",
              "LD0/CALH1/GrWrn/stVal": "Реле Вызов",
              "LD0/C_TCTR1/Beh/q": "",
              "LD0/C_TCTR1/Beh/stVal": "850_ALL_BEH",
              "LD0/C_TCTR1/EEHealth/q": "",
              "LD0/C_TCTR1/EEHealth/stVal": "850_TCTR1_HEAL",
              "LD0/GSE_GGIO1/Beh/q": "",
              "LD0/GSE_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/G_TCTR1/Beh/q": "",
              "LD0/G_TCTR1/Beh/stVal": "850_ALL_BEH",
              "LD0/G_TVTR1/Beh/q": "",
              "LD0/G_TVTR1/Beh/stVal": "850_ALL_BEH",
              "LD0/In_GGIO1/Beh/q": "",
              "LD0/In_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/In_GGIO1/Ind1/q": "",
              "LD0/In_GGIO1/Ind1/stVal": "[Я1] Вход",
              "LD0/In_GGIO1/Ind10/q": "",
              "LD0/In_GGIO1/Ind10/stVal": "[Я10] Вход",
              "LD0/In_GGIO1/Ind11/q": "",
              "LD0/In_GGIO1/Ind11/stVal": "[Я11] Вход",
              "LD0/In_GGIO1/Ind12/q": "",
              "LD0/In_GGIO1/Ind12/stVal": "[Я12] Вход",
              "LD0/In_GGIO1/Ind13/q": "",
              "LD0/In_GGIO1/Ind13/stVal": "[Я13] Вход",
              "LD0/In_GGIO1/Ind14/q": "",
              "LD0/In_GGIO1/Ind14/stVal": "[Я14] Вход",
              "LD0/In_GGIO1/Ind15/q": "",
              "LD0/In_GGIO1/Ind15/stVal": "[Я15] Вход",
              "LD0/In_GGIO1/Ind16/q": "",
              "LD0/In_GGIO1/Ind16/stVal": "[Я16] Вход",
              "LD0/In_GGIO1/Ind17/q": "",
              "LD0/In_GGIO1/Ind17/stVal": "[Я17] Вход",
              "LD0/In_GGIO1/Ind18/q": "",
              "LD0/In_GGIO1/Ind18/stVal": "[Я18] Вход",
              "LD0/In_GGIO1/Ind19/q": "",
              "LD0/In_GGIO1/Ind19/stVal": "[Я19] Вход",
              "LD0/In_GGIO1/Ind2/q": "",
              "LD0/In_GGIO1/Ind2/stVal": "[Я2] Вход",
              "LD0/In_GGIO1/Ind20/q": "",
              "LD0/In_GGIO1/Ind20/stVal": "[Я20] Вход",
              "LD0/In_GGIO1/Ind21/q": "",
              "LD0/In_GGIO1/Ind21/stVal": "[Я21] Вход",
              "LD0/In_GGIO1/Ind22/q": "",
              "LD0/In_GGIO1/Ind22/stVal": "[Я22] Вход",
              "LD0/In_GGIO1/Ind3/q": "",
              "LD0/In_GGIO1/Ind3/stVal": "[Я3] Вход",
              "LD0/In_GGIO1/Ind4/q": "",
              "LD0/In_GGIO1/Ind4/stVal": "[Я4] Вход",
              "LD0/In_GGIO1/Ind5/q": "",
              "LD0/In_GGIO1/Ind5/stVal": "[Я5] Вход",
              "LD0/In_GGIO1/Ind6/q": "",
              "LD0/In_GGIO1/Ind6/stVal": "[Я6] Вход",
              "LD0/In_GGIO1/Ind7/q": "",
              "LD0/In_GGIO1/Ind7/stVal": "[Я7] Вход",
              "LD0/In_GGIO1/Ind8/q": "",
              "LD0/In_GGIO1/Ind8/stVal": "[Я8] Вход",
              "LD0/In_GGIO1/Ind9/q": "",
              "LD0/In_GGIO1/Ind9/stVal": "[Я9] Вход",
              "LD0/LLN0/Beh/q": "",
              "LD0/LLN0/Beh/stVal": "850_ALL_BEH",
              "LD0/LLN0/Health/q": "",
              "LD0/LLN0/Health/stVal": "850_DEV_HEAL",
              "LD0/LLN0/LocKey/q": "",
              "LD0/LLN0/LocKey/stVal": "МУ",
              "LD0/LLN0/Mod/q": "",
              "LD0/LLN0/Mod/stVal": "850_LLN0_MOD",
              "LD0/LPHD1/PhyHealth/q": "",
              "LD0/LPHD1/PhyHealth/stVal": "850_DEV_HEAL",
              "LD0/MT_MMXU1/A/phsA/cVal/ang/f": "ang(IA), гр_ТИ",
              "LD0/MT_MMXU1/A/phsA/cVal/mag/f": "IA, А_ТИ",
              "LD0/MT_MMXU1/A/phsA/q": "850_I_Q",
              "LD0/MT_MMXU1/A/phsB/cVal/ang/f": "ang(IB), гр_ТИ",
              "LD0/MT_MMXU1/A/phsB/cVal/mag/f": "IB, А_ТИ",
              "LD0/MT_MMXU1/A/phsB/q": "850_I_Q",
              "LD0/MT_MMXU1/A/phsC/cVal/ang/f": "ang(IC), гр_ТИ",
              "LD0/MT_MMXU1/A/phsC/cVal/mag/f": "IC, А_ТИ",
              "LD0/MT_MMXU1/A/phsC/q": "850_I_Q",
              "LD0/MT_MMXU1/A/res/cVal/ang/f": "ang(3I0), гр_ТИ",
              "LD0/MT_MMXU1/A/res/cVal/mag/f": "3I0, А_ТИ",
              "LD0/MT_MMXU1/A/res/q": "850_I_Q",
              "LD0/MT_MMXU1/Beh/q": "",
              "LD0/MT_MMXU1/Beh/stVal": "850_ALL_BEH",
              "LD0/MT_MMXU1/Hz/mag/f": "F, Гц_ТИ",
              "LD0/MT_MMXU1/Hz/q": "850_Frq_Q",
              "LD0/MT_MMXU1/PNV/res/cVal/ang/f": "ang(3U0), гр_ТИ",
              "LD0/MT_MMXU1/PNV/res/cVal/mag/f": "3U0, В_ТИ",
              "LD0/MT_MMXU1/PNV/res/q": "850_U_Q",
              "LD0/MT_MMXU1/PPV/phsAB/cVal/ang/f": "ang(UAB), гр_ТИ",
              "LD0/MT_MMXU1/PPV/phsAB/cVal/mag/f": "UAB, В_ТИ",
              "LD0/MT_MMXU1/PPV/phsAB/q": "850_U_Q",
              "LD0/MT_MMXU1/PPV/phsBC/cVal/ang/f": "ang(UBC), гр_ТИ",
              "LD0/MT_MMXU1/PPV/phsBC/cVal/mag/f": "UBC, В_ТИ",
              "LD0/MT_MMXU1/PPV/phsBC/q": "850_U_Q",
              "LD0/MT_MMXU1/PPV/phsCA/cVal/ang/f": "ang(UCA), гр_ТИ",
              "LD0/MT_MMXU1/PPV/phsCA/cVal/mag/f": "UCA, В_ТИ",
              "LD0/MT_MMXU1/PPV/phsCA/q": "850_U_Q",
              "LD0/MT_MMXU1/PPV2/phsBC/cVal/ang/f": "ang(Uтн2), гр_ТИ",
              "LD0/MT_MMXU1/PPV2/phsBC/cVal/mag/f": "Uтн2, В_ТИ",
              "LD0/MT_MMXU1/PPV2/phsBC/q": "",
              "LD0/Out_GGIO1/Beh/q": "",
              "LD0/Out_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/Out_GGIO1/Ind1/q": "",
              "LD0/Out_GGIO1/Ind1/stVal": "[K1] Выход",
              "LD0/Out_GGIO1/Ind10/q": "",
              "LD0/Out_GGIO1/Ind10/stVal": "[K10] Выход",
              "LD0/Out_GGIO1/Ind11/q": "",
              "LD0/Out_GGIO1/Ind11/stVal": "[K11] Выход",
              "LD0/Out_GGIO1/Ind12/q": "",
              "LD0/Out_GGIO1/Ind12/stVal": "[K12] Выход",
              "LD0/Out_GGIO1/Ind13/q": "",
              "LD0/Out_GGIO1/Ind13/stVal": "[K13] Выход",
              "LD0/Out_GGIO1/Ind14/q": "",
              "LD0/Out_GGIO1/Ind14/stVal": "[K14] Выход",
              "LD0/Out_GGIO1/Ind15/q": "",
              "LD0/Out_GGIO1/Ind15/stVal": "[K15] Выход",
              "LD0/Out_GGIO1/Ind16/q": "",
              "LD0/Out_GGIO1/Ind16/stVal": "[K16] Выход",
              "LD0/Out_GGIO1/Ind17/q": "",
              "LD0/Out_GGIO1/Ind17/stVal": "[K17] Выход",
              "LD0/Out_GGIO1/Ind18/q": "",
              "LD0/Out_GGIO1/Ind18/stVal": "[K18] Выход",
              "LD0/Out_GGIO1/Ind19/q": "",
              "LD0/Out_GGIO1/Ind19/stVal": "[K19] Выход",
              "LD0/Out_GGIO1/Ind2/q": "",
              "LD0/Out_GGIO1/Ind2/stVal": "[K2] Выход",
              "LD0/Out_GGIO1/Ind20/q": "",
              "LD0/Out_GGIO1/Ind20/stVal": "[K20] Выход",
              "LD0/Out_GGIO1/Ind21/q": "",
              "LD0/Out_GGIO1/Ind21/stVal": "[K21] Выход",
              "LD0/Out_GGIO1/Ind3/q": "",
              "LD0/Out_GGIO1/Ind3/stVal": "[K3] Выход",
              "LD0/Out_GGIO1/Ind4/q": "",
              "LD0/Out_GGIO1/Ind4/stVal": "[K4] Отказ БМРЗ",
              "LD0/Out_GGIO1/Ind5/q": "",
              "LD0/Out_GGIO1/Ind5/stVal": "[K5] Выход",
              "LD0/Out_GGIO1/Ind6/q": "",
              "LD0/Out_GGIO1/Ind6/stVal": "[K6] Выход",
              "LD0/Out_GGIO1/Ind7/q": "",
              "LD0/Out_GGIO1/Ind7/stVal": "[K7] Выход",
              "LD0/Out_GGIO1/Ind8/q": "",
              "LD0/Out_GGIO1/Ind8/stVal": "[K8] Выход",
              "LD0/Out_GGIO1/Ind9/q": "",
              "LD0/Out_GGIO1/Ind9/stVal": "[K9] Выход",
              "LD0/PTRC1/Beh/q": "",
              "LD0/PTRC1/Beh/stVal": "850_ALL_BEH",
              "LD0/PTRC1/OpCntRs/q": "",
              "LD0/PTRC1/OpCntRs/stVal": "Количество откл.",
              "LD0/PTRC1/Tr/general": "850_Срабатывание защит",
              "LD0/PTRC1/Tr/q": "",
              "LD0/PTUF1/Beh/q": "",
              "LD0/PTUF1/Beh/stVal": "850_ALL_BEH",
              "LD0/PTUF1/Op/general": "АЧР.1 сраб.",
              "LD0/PTUF1/Op/q": "",
              "LD0/PTUF1/OpCntRs/q": "",
              "LD0/PTUF1/OpCntRs/stVal": "Сраб. АЧР.1",
              "LD0/PTUF1/Str/general": "АЧР.1 пуск",
              "LD0/PTUF1/Str/q": "",
              "LD0/PTUF2/Beh/q": "",
              "LD0/PTUF2/Beh/stVal": "850_ALL_BEH",
              "LD0/PTUF2/Op/general": "АЧР.2 сраб.",
              "LD0/PTUF2/Op/q": "",
              "LD0/PTUF2/OpCntRs/q": "",
              "LD0/PTUF2/OpCntRs/stVal": "Сраб. АЧР.2",
              "LD0/PTUF2/Str/general": "АЧР.2 пуск",
              "LD0/PTUF2/Str/q": "",
              "LD0/PTUF3/Beh/q": "",
              "LD0/PTUF3/Beh/stVal": "850_ALL_BEH",
              "LD0/PTUF3/Op/general": "АЧР.3 сраб.",
              "LD0/PTUF3/Op/q": "",
              "LD0/PTUF3/OpCntRs/q": "",
              "LD0/PTUF3/OpCntRs/stVal": "Сраб. АЧР.3",
              "LD0/PTUF3/Str/general": "АЧР.3 пуск",
              "LD0/PTUF3/Str/q": "",
              "LD0/PTUV1/Beh/q": "",
              "LD0/PTUV1/Beh/stVal": "850_ALL_BEH",
              "LD0/PTUV1/Op/general": "АРСН.1 сраб.",
              "LD0/PTUV1/Op/q": "",
              "LD0/PTUV1/OpCntRs/q": "",
              "LD0/PTUV1/OpCntRs/stVal": "Сраб. АРСН.1",
              "LD0/PTUV1/Str/general": "АРСН.1 пуск",
              "LD0/PTUV1/Str/q": "",
              "LD0/PTUV2/Beh/q": "",
              "LD0/PTUV2/Beh/stVal": "850_ALL_BEH",
              "LD0/PTUV2/Op/general": "АРСН.2 сраб.",
              "LD0/PTUV2/Op/q": "",
              "LD0/PTUV2/OpCntRs/q": "",
              "LD0/PTUV2/OpCntRs/stVal": "Сраб. АРСН.2",
              "LD0/PTUV2/Str/general": "АРСН.2 пуск",
              "LD0/PTUV2/Str/q": "",
              "LD0/PTUV3/Beh/q": "",
              "LD0/PTUV3/Beh/stVal": "850_ALL_BEH",
              "LD0/PTUV3/Op/general": "АРСН.3 сраб.",
              "LD0/PTUV3/Op/q": "",
              "LD0/PTUV3/OpCntRs/q": "",
              "LD0/PTUV3/OpCntRs/stVal": "Сраб. АРСН.3",
              "LD0/PTUV3/Str/general": "АРСН.3 пуск",
              "LD0/PTUV3/Str/q": "",
              "LD0/Prec_MMXU1/A/phsA/cVal/ang/f": "ang(Iф), гр_ТИ",
              "LD0/Prec_MMXU1/A/phsA/cVal/mag/f": "Iф, А_ТИ",
              "LD0/Prec_MMXU1/A/phsA/q": "850_I_Q",
              "LD0/Prec_MMXU1/Beh/q": "",
              "LD0/Prec_MMXU1/Beh/stVal": "850_ALL_BEH",
              "LD0/Pwr_MMXU1/Beh/q": "",
              "LD0/Pwr_MMXU1/Beh/stVal": "850_ALL_BEH",
              "LD0/Pwr_MMXU1/TotPF/mag/f": "cos(ф)_ТИ",
              "LD0/Pwr_MMXU1/TotPF/q": "850_PF_Q",
              "LD0/Pwr_MMXU1/TotVA/mag/f": "S, кВА_ТИ",
              "LD0/Pwr_MMXU1/TotVA/q": "850_S_Q",
              "LD0/Pwr_MMXU1/TotVAr/mag/f": "Q, квар_ТИ",
              "LD0/Pwr_MMXU1/TotVAr/q": "850_Q_Q",
              "LD0/Pwr_MMXU1/TotW/mag/f": "P, кВт_ТИ",
              "LD0/Pwr_MMXU1/TotW/q": "850_P_Q",
              "LD0/Q1_CSWI1/Beh/q": "",
              "LD0/Q1_CSWI1/Beh/stVal": "850_CSWI_BEH",
              "LD0/Q1_CSWI1/Mod/q": "",
              "LD0/Q1_CSWI1/Mod/stVal": "850_CSWI_MOD",
              "LD0/Q1_CSWI1/OpCls/general": "850_Реле включить",
              "LD0/Q1_CSWI1/OpCls/q": "",
              "LD0/Q1_CSWI1/OpOpn/general": "850_Реле отключить",
              "LD0/Q1_CSWI1/OpOpn/q": "",
              "LD0/Q1_CSWI1/Pos/q": "",
              "LD0/Q1_CSWI1/Pos/stVal": "850_XCBR_POS",
              "LD0/Q1_RBRF1/Beh/q": "",
              "LD0/Q1_RBRF1/Beh/stVal": "850_ALL_BEH",
              "LD0/Q1_RBRF1/OpCntRs/q": "",
              "LD0/Q1_RBRF1/OpCntRs/stVal": "Сраб. УРОВ",
              "LD0/Q1_RBRF1/OpEx/general": "УРОВ сраб.",
              "LD0/Q1_RBRF1/OpEx/q": "",
              "LD0/Q1_RREC1/AutoRecSt/q": "",
              "LD0/Q1_RREC1/AutoRecSt/stVal": "850_RREC_State",
              "LD0/Q1_RREC1/Beh/q": "",
              "LD0/Q1_RREC1/Beh/stVal": "850_ALL_BEH",
              "LD0/Q1_RREC1/Op11Cnt/q": "",
              "LD0/Q1_RREC1/Op11Cnt/stVal": "Пуск АПВ.1 1",
              "LD0/Q1_RREC1/Op11FailCnt/q": "",
              "LD0/Q1_RREC1/Op11FailCnt/stVal": "АПВ.1 1 неусп.",
              "LD0/Q1_RREC1/Op11SuccCnt/q": "",
              "LD0/Q1_RREC1/Op11SuccCnt/stVal": "АПВ.1 1 усп.",
              "LD0/Q1_RREC1/Op12Cnt/q": "",
              "LD0/Q1_RREC1/Op12Cnt/stVal": "Пуск АПВ.1 2",
              "LD0/Q1_RREC1/Op12FailCnt/q": "",
              "LD0/Q1_RREC1/Op12FailCnt/stVal": "АПВ.1 2 неусп.",
              "LD0/Q1_RREC1/Op12SuccCnt/q": "",
              "LD0/Q1_RREC1/Op12SuccCnt/stVal": "АПВ.1 2 усп.",
              "LD0/Q1_RREC1/Op21Cnt/q": "",
              "LD0/Q1_RREC1/Op21Cnt/stVal": "Пуск АПВ.2 1",
              "LD0/Q1_RREC1/Op21FailCnt/q": "",
              "LD0/Q1_RREC1/Op21FailCnt/stVal": "АПВ.2 1 неусп.",
              "LD0/Q1_RREC1/Op21SuccCnt/q": "",
              "LD0/Q1_RREC1/Op21SuccCnt/stVal": "АПВ.2 1 усп.",
              "LD0/Q1_RREC1/Op22Cnt/q": "",
              "LD0/Q1_RREC1/Op22Cnt/stVal": "Пуск АПВ.2 2",
              "LD0/Q1_RREC1/Op22FailCnt/q": "",
              "LD0/Q1_RREC1/Op22FailCnt/stVal": "АПВ.2 2 неусп.",
              "LD0/Q1_RREC1/Op22SuccCnt/q": "",
              "LD0/Q1_RREC1/Op22SuccCnt/stVal": "АПВ.2 2 усп.",
              "LD0/Q1_RREC1/OpCls/general": "АПВ.1 сраб.",
              "LD0/Q1_RREC1/OpCls/q": "",
              "LD0/Q1_RSYN1/Beh/q": "",
              "LD0/Q1_RSYN1/Beh/stVal": "850_ALL_BEH",
              "LD0/Q1_RSYN1/Blk/q": "",
              "LD0/Q1_RSYN1/Blk/stVal": "850_RSYN_BLK",
              "LD0/Q1_RSYN1/Rel/q": "",
              "LD0/Q1_RSYN1/Rel/stVal": "Вкл. с синхр.",
              "LD0/Q1_SCBR1/AccAbr/mag/f": "850_SCBR_ABR",
              "LD0/Q1_SCBR1/AccAbr/q": "",
              "LD0/Q1_SCBR1/Beh/q": "",
              "LD0/Q1_SCBR1/Beh/stVal": "850_ALL_BEH",
              "LD0/Q1_SCBR1/ColOpn/q": "",
              "LD0/Q1_SCBR1/ColOpn/stVal": "850_SCBR1_ColOpn",
              "LD0/Q1_SCBR1/ColOpn2/q": "",
              "LD0/Q1_SCBR1/ColOpn2/stVal": "850_SCBR1_ColOpn2",
              "LD0/Q1_SCBR1/MechHealth/q": "",
              "LD0/Q1_SCBR1/MechHealth/stVal": "850_XCBR_HEAL",
              "LD0/Q1_SCBR1/RctTmOpn/mag/f": "850_SCBR_TMOPN",
              "LD0/Q1_SCBR1/RctTmOpn/q": "",
              "LD0/Q1_SIMG1/Beh/q": "",
              "LD0/Q1_SIMG1/Beh/stVal": "850_ALL_BEH",
              "LD0/Q1_SIMG1/InsAlm/q": "",
              "LD0/Q1_SIMG1/InsAlm/stVal": "850_SIMG_ALM",
              "LD0/Q1_SIMG1/InsBlk/q": "",
              "LD0/Q1_SIMG1/InsBlk/stVal": "850_SIMG_BLK",
              "LD0/Q1_SIMG1/InsTr/q": "",
              "LD0/Q1_SIMG1/InsTr/stVal": "850_SIMG_TR",
              "LD0/Q1_XCBR1/Beh/q": "",
              "LD0/Q1_XCBR1/Beh/stVal": "850_ALL_BEH",
              "LD0/Q1_XCBR1/BlkCls/q": "",
              "LD0/Q1_XCBR1/BlkCls/stVal": "850_Включение блок.",
              "LD0/Q1_XCBR1/BlkOpn/q": "",
              "LD0/Q1_XCBR1/BlkOpn/stVal": "850_XCBR_BLKOPN",
              "LD0/Q1_XCBR1/EEHealth/q": "",
              "LD0/Q1_XCBR1/EEHealth/stVal": "850_XCBR_HEAL",
              "LD0/Q1_XCBR1/Loc/q": "",
              "LD0/Q1_XCBR1/Loc/stVal": "850_XCBR_LOC",
              "LD0/Q1_XCBR1/OpCnt/q": "",
              "LD0/Q1_XCBR1/OpCnt/stVal": "Количество откл.",
              "LD0/Q1_XCBR1/Pos/q": "",
              "LD0/Q1_XCBR1/Pos/stVal": "850_XCBR_POS",
              "LD0/RDRE1/Beh/q": "",
              "LD0/RDRE1/Beh/stVal": "850_ALL_BEH",
              "LD0/RDRE1/RcdMade/q": "",
              "LD0/RDRE1/RcdMade/stVal": "850_RDRE_Made",
              "LD0/RDRE1/RcdStr/q": "",
              "LD0/RDRE1/RcdStr/stVal": "850_RDRE_Str",
              "LD0/RFLO1/Beh/q": "",
              "LD0/RFLO1/Beh/stVal": "850_ALL_BEH",
              "LD0/RFLO1/FltDiskm/mag/f": "ОМП, км",
              "LD0/RFLO1/FltDiskm/q": "850_RFLO_Q",
              "LD0/RFLO1/FltLoop/q": "850_RFLO_ZL_Q",
              "LD0/RFLO1/FltLoop/stVal": "850_RFLO_Loop",
              "LD0/RFLO1/FltZ/cVal/ang/f": "850_RFLO_ZAng",
              "LD0/RFLO1/FltZ/cVal/mag/f": "850_RFLO_ZAbs",
              "LD0/RFLO1/FltZ/q": "850_RFLO_ZL_Q",
              "LD0/RPSB1/Beh/q": "",
              "LD0/RPSB1/Beh/stVal": "850_ALL_BEH",
              "LD0/RPSB1/BlkZn/q": "",
              "LD0/RPSB1/BlkZn/stVal": "850_RPSB_BLK",
              "LD0/RPSB1/Str/general": "850_RPSB_STR",
              "LD0/RPSB1/Str/q": "",
              "LD0/SARC1/Beh/q": "",
              "LD0/SARC1/Beh/stVal": "850_ALL_BEH",
              "LD0/SARC1/FACntRs/q": "",
              "LD0/SARC1/FACntRs/stVal": "Сраб. ДгЗ",
              "LD0/SARC1/FADet/q": "",
              "LD0/SARC1/FADet/stVal": "ДгЗ сраб.",
              "LD0/SARC1/Health/q": "",
              "LD0/SARC1/Health/stVal": "850_SARC_HEAL",
              "LD0/Seq_MSQI1/Beh/q": "",
              "LD0/Seq_MSQI1/Beh/stVal": "850_ALL_BEH",
              "LD0/Seq_MSQI1/SeqA/c1/cVal/ang/f": "ang(I1), гр_ТИ",
              "LD0/Seq_MSQI1/SeqA/c1/cVal/mag/f": "I1, А_ТИ",
              "LD0/Seq_MSQI1/SeqA/c1/q": "850_I_Q",
              "LD0/Seq_MSQI1/SeqA/c2/cVal/ang/f": "ang(I2), гр_ТИ",
              "LD0/Seq_MSQI1/SeqA/c2/cVal/mag/f": "I2, А_ТИ",
              "LD0/Seq_MSQI1/SeqA/c2/q": "850_I_Q",
              "LD0/Seq_MSQI1/SeqA/c3/cVal/ang/f": "ang(3I0 расч.), гр_ТИ",
              "LD0/Seq_MSQI1/SeqA/c3/cVal/mag/f": "3I0 расч., А_ТИ",
              "LD0/Seq_MSQI1/SeqA/c3/q": "850_I_Q",
              "LD0/Seq_MSQI1/SeqV/c1/cVal/ang/f": "ang(U1), гр_ТИ",
              "LD0/Seq_MSQI1/SeqV/c1/cVal/mag/f": "U1, В_ТИ",
              "LD0/Seq_MSQI1/SeqV/c1/q": "850_U_Q",
              "LD0/Seq_MSQI1/SeqV/c2/cVal/ang/f": "ang(U2), гр_ТИ",
              "LD0/Seq_MSQI1/SeqV/c2/cVal/mag/f": "U2, В_ТИ",
              "LD0/Seq_MSQI1/SeqV/c2/q": "850_U_Q",
              "LD0/Seq_MSQI1/SeqV/c3/cVal/ang/f": "ang(3U0), гр_ТИ",
              "LD0/Seq_MSQI1/SeqV/c3/cVal/mag/f": "3U0, В_ТИ",
              "LD0/Seq_MSQI1/SeqV/c3/q": "850_U_Q",
              "LD0/SetACHRAB_GGIO1/Beh/q": "",
              "LD0/SetACHRAB_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetACHR_GGIO1/Beh/q": "",
              "LD0/SetACHR_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetACHR_GGIO2/Beh/q": "",
              "LD0/SetACHR_GGIO2/Beh/stVal": "850_ALL_BEH",
              "LD0/SetACHR_GGIO3/Beh/q": "",
              "LD0/SetACHR_GGIO3/Beh/stVal": "850_ALL_BEH",
              "LD0/SetAPV_GGIO1/Beh/q": "",
              "LD0/SetAPV_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetAPV_GGIO2/Beh/q": "",
              "LD0/SetAPV_GGIO2/Beh/stVal": "850_ALL_BEH",
              "LD0/SetAVR_GGIO1/Beh/q": "",
              "LD0/SetAVR_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetCHAPV_GGIO1/Beh/q": "",
              "LD0/SetCHAPV_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetCHAPV_GGIO2/Beh/q": "",
              "LD0/SetCHAPV_GGIO2/Beh/stVal": "850_ALL_BEH",
              "LD0/SetCHAPV_GGIO3/Beh/q": "",
              "LD0/SetCHAPV_GGIO3/Beh/stVal": "850_ALL_BEH",
              "LD0/SetDGZ_GGIO1/Beh/q": "",
              "LD0/SetDGZ_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetDIAG_GGIO1/Beh/q": "",
              "LD0/SetDIAG_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetDZDV_GGIO1/Beh/q": "",
              "LD0/SetDZDV_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetDZMF_GGIO1/Beh/q": "",
              "LD0/SetDZMF_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetKCN_GGIO1/Beh/q": "",
              "LD0/SetKCN_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetKCT_GGIO1/Beh/q": "",
              "LD0/SetKCT_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetKM_GGIO1/Beh/q": "",
              "LD0/SetKM_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetKN_GGIO1/Beh/q": "",
              "LD0/SetKN_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetLZSH_GGIO1/Beh/q": "",
              "LD0/SetLZSH_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetMTZ_GGIO1/Beh/q": "",
              "LD0/SetMTZ_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetOSC_GGIO1/Beh/q": "",
              "LD0/SetOSC_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetOTHER_GGIO1/Beh/q": "",
              "LD0/SetOTHER_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetRAVR_GGIO1/Beh/q": "",
              "LD0/SetRAVR_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetRES_GGIO1/Beh/q": "",
              "LD0/SetRES_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetSYN_GGIO1/Beh/q": "",
              "LD0/SetSYN_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetTO_GGIO1/Beh/q": "",
              "LD0/SetTO_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetUBK_GGIO1/Beh/q": "",
              "LD0/SetUBK_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetUDZDV_GGIO1/Beh/q": "",
              "LD0/SetUDZDV_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetUDZMF_GGIO1/Beh/q": "",
              "LD0/SetUDZMF_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetUMTZ_GGIO1/Beh/q": "",
              "LD0/SetUMTZ_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetUROV_GGIO1/Beh/q": "",
              "LD0/SetUROV_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetVNR_GGIO1/Beh/q": "",
              "LD0/SetVNR_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetVYZ_GGIO1/Beh/q": "",
              "LD0/SetVYZ_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetZMN_GGIO1/Beh/q": "",
              "LD0/SetZMN_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetZOF_GGIO1/Beh/q": "",
              "LD0/SetZOF_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetZOZZ_GGIO1/Beh/q": "",
              "LD0/SetZOZZ_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetZPN_GGIO1/Beh/q": "",
              "LD0/SetZPN_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/SetZPP_GGIO1/Beh/q": "",
              "LD0/SetZPP_GGIO1/Beh/stVal": "850_ALL_BEH",
              "LD0/TN2_TVTR2/Beh/q": "",
              "LD0/TN2_TVTR2/Beh/stVal": "850_ALL_BEH",
              "LD0/TN2_TVTR2/EEHealth/q": "",
              "LD0/TN2_TVTR2/EEHealth/stVal": "850_TVTR2_HEAL",
              "LD0/User_GAPC1/Beh/q": "",
              "LD0/User_GAPC1/Beh/stVal": "850_ALL_BEH",
              "LD0/Z_MMXU1/Beh/q": "",
              "LD0/Z_MMXU1/Beh/stVal": "850_ALL_BEH",
              "LD0/Z_MMXU1/Z/phsA/cVal/ang/f": "ang(ZAB), гр_ТИ",
              "LD0/Z_MMXU1/Z/phsA/cVal/mag/f": "ZAB, Ом_ТИ",
              "LD0/Z_MMXU1/Z/phsA/q": "850_ZAB_Q",
              "LD0/Z_MMXU1/Z/phsB/cVal/ang/f": "ang(ZBC), гр_ТИ",
              "LD0/Z_MMXU1/Z/phsB/cVal/mag/f": "ZBC, Ом_ТИ",
              "LD0/Z_MMXU1/Z/phsB/q": "850_ZBC_Q",
              "LD0/Z_MMXU1/Z/phsC/cVal/ang/f": "ang(ZCA), гр_ТИ",
              "LD0/Z_MMXU1/Z/phsC/cVal/mag/f": "ZCA, Ом_ТИ",
              "LD0/Z_MMXU1/Z/phsC/q": "850_ZCA_Q",
              "LD0/Z_MMXU2/Beh/q": "",
              "LD0/Z_MMXU2/Beh/stVal": "850_ALL_BEH",
              "LD0/Z_MMXU2/Z/phsA/cVal/ang/f": "ang(ZA0), гр_ТИ",
              "LD0/Z_MMXU2/Z/phsA/cVal/mag/f": "ZA0, Ом_ТИ",
              "LD0/Z_MMXU2/Z/phsA/q": "850_ZA0_Q",
              "LD0/Z_MMXU2/Z/phsB/cVal/ang/f": "ang(ZB0), гр_ТИ",
              "LD0/Z_MMXU2/Z/phsB/cVal/mag/f": "ZB0, Ом_ТИ",
              "LD0/Z_MMXU2/Z/phsB/q": "850_ZB0_Q",
              "LD0/Z_MMXU2/Z/phsC/cVal/ang/f": "ang(ZC0), гр_ТИ",
              "LD0/Z_MMXU2/Z/phsC/cVal/mag/f": "ZC0, Ом_ТИ",
              "LD0/Z_MMXU2/Z/phsC/q": "850_ZC0_Q",
              "LD0/AB_TVTR1/Rat/setMag/f": "Ктр U",
              "LD0/A_TCTR1/Rat/setMag/f": "Ктр I",
              "LD0/BC_TVTR1/Rat/setMag/f": "Ктр U",
              "LD0/B_TCTR1/Rat/setMag/f": "Ктр I",
              "LD0/C_TCTR1/Rat/setMag/f": "Ктр I",
              "LD0/G_TCTR1/Rat/setMag/f": "Ктр 3I0",
              "LD0/G_TVTR1/Rat/setMag/f": "Ктр 3U0",
              "LD0/RFLO1/Enable/setVal": "ОМП S1",
              "LD0/RFLO1/ILNom/setMag/f": "ОМП Iл.ном",
              "LD0/RFLO1/L1/setMag/f": "ОМП L(1)",
              "LD0/RFLO1/L2/setMag/f": "ОМП L(2)",
              "LD0/RFLO1/L3/setMag/f": "ОМП L(3)",
              "LD0/RFLO1/L4/setMag/f": "ОМП L(4)",
              "LD0/RFLO1/L5/setMag/f": "ОМП L(5)",
              "LD0/RFLO1/L6/setMag/f": "ОМП L(6)",
              "LD0/RFLO1/L7/setMag/f": "ОМП L(7)",
              "LD0/RFLO1/L8/setMag/f": "ОМП L(8)",
              "LD0/RFLO1/LCnt/setVal": "ОМП N лин",
              "LD0/RFLO1/X1/setMag/f": "ОМП X1(1)",
              "LD0/RFLO1/X2/setMag/f": "ОМП X1(2)",
              "LD0/RFLO1/X3/setMag/f": "ОМП X1(3)",
              "LD0/RFLO1/X4/setMag/f": "ОМП X1(4)",
              "LD0/RFLO1/X5/setMag/f": "ОМП X1(5)",
              "LD0/RFLO1/X6/setMag/f": "ОМП X1(6)",
              "LD0/RFLO1/X7/setMag/f": "ОМП X1(7)",
              "LD0/RFLO1/X8/setMag/f": "ОМП X1(8)",
              "LD0/SetACHRAB_GGIO1/ACHRCHAPVS1/setVal": "АЧР/ЧАПВ S1",
              "LD0/SetACHRAB_GGIO1/ACHRLS1/setVal": "АЧРл S1",
              "LD0/SetACHRAB_GGIO1/ACHRLT/setVal": "АЧРл Т",
              "LD0/SetACHRAB_GGIO1/CHAPVLS1/setVal": "ЧАПВл S1",
              "LD0/SetACHRAB_GGIO1/CHAPVLT/setVal": "ЧАПВл Т",
              "LD0/SetACHRAB_GGIO1/CHAPVLTgot/setVal": "ЧАПВл Тгот",
              "LD0/SetACHR_GGIO1/ACHR1F/setMag/f": "АЧР-1.1 F",
              "LD0/SetACHR_GGIO1/ACHR1S1/setVal": "АЧР-1.1 S1",
              "LD0/SetACHR_GGIO1/ACHR1S2/setVal": "АЧР-1.1 S2",
              "LD0/SetACHR_GGIO1/ACHR1T/setVal": "АЧР-1.1 Т",
              "LD0/SetACHR_GGIO1/ACHR1dFdt/setMag/f": "АЧР-1.1 dF/dt",
              "LD0/SetACHR_GGIO1/ACHR2Fp/setMag/f": "АЧР-2.1 F(п)",
              "LD0/SetACHR_GGIO1/ACHR2Fv/setMag/f": "АЧР-2.1 F(в)",
              "LD0/SetACHR_GGIO1/ACHR2S1/setVal": "АЧР-2.1 S1",
              "LD0/SetACHR_GGIO1/ACHR2S2/setVal": "АЧР-2.1 S2",
              "LD0/SetACHR_GGIO1/ACHR2Tf/setVal": "АЧР-2.1 Тf",
              "LD0/SetACHR_GGIO1/ACHR2Tu/setVal": "АЧР-2.1 Тu",
              "LD0/SetACHR_GGIO1/ACHR2U/setMag/f": "АЧР-2.1 U",
              "LD0/SetACHR_GGIO1/ACHRCF/setMag/f": "АЧР-С.1 F",
              "LD0/SetACHR_GGIO1/ACHRCS1/setVal": "АЧР-С.1 S1",
              "LD0/SetACHR_GGIO1/ACHRCdFdt/setMag/f": "АЧР-С.1 dF/dt",
              "LD0/SetACHR_GGIO1/ACHRTimp/setVal": "АЧР.1 Тимп",
              "LD0/SetACHR_GGIO1/ARSNS1/setVal": "АРСН.1 S1",
              "LD0/SetACHR_GGIO1/ARSNS2/setVal": "АРСН.1 S2",
              "LD0/SetACHR_GGIO1/ARSNT/setVal": "АРСН.1 Т",
              "LD0/SetACHR_GGIO1/ARSNTimp/setVal": "АРСН.1 Тимп",
              "LD0/SetACHR_GGIO1/ARSNU/setMag/f": "АРСН.1 U",
              "LD0/SetACHR_GGIO1/ARSNU2/setMag/f": "АРСН.1 U2",
              "LD0/SetACHR_GGIO2/ACHR1F/setMag/f": "АЧР-1.2 F",
              "LD0/SetACHR_GGIO2/ACHR1S1/setVal": "АЧР-1.2 S1",
              "LD0/SetACHR_GGIO2/ACHR1S2/setVal": "АЧР-1.2 S2",
              "LD0/SetACHR_GGIO2/ACHR1T/setVal": "АЧР-1.2 Т",
              "LD0/SetACHR_GGIO2/ACHR1dFdt/setMag/f": "АЧР-1.2 dF/dt",
              "LD0/SetACHR_GGIO2/ACHR2Fp/setMag/f": "АЧР-2.2 F(п)",
              "LD0/SetACHR_GGIO2/ACHR2Fv/setMag/f": "АЧР-2.2 F(в)",
              "LD0/SetACHR_GGIO2/ACHR2S1/setVal": "АЧР-2.2 S1",
              "LD0/SetACHR_GGIO2/ACHR2S2/setVal": "АЧР-2.2 S2",
              "LD0/SetACHR_GGIO2/ACHR2Tf/setVal": "АЧР-2.2 Тf",
              "LD0/SetACHR_GGIO2/ACHR2Tu/setVal": "АЧР-2.2 Тu",
              "LD0/SetACHR_GGIO2/ACHR2U/setMag/f": "АЧР-2.2 U",
              "LD0/SetACHR_GGIO2/ACHRCF/setMag/f": "АЧР-С.2 F",
              "LD0/SetACHR_GGIO2/ACHRCS1/setVal": "АЧР-С.2 S1",
              "LD0/SetACHR_GGIO2/ACHRCdFdt/setMag/f": "АЧР-С.2 dF/dt",
              "LD0/SetACHR_GGIO2/ACHRTimp/setVal": "АЧР.2 Тимп",
              "LD0/SetACHR_GGIO2/ARSNS1/setVal": "АРСН.2 S1",
              "LD0/SetACHR_GGIO2/ARSNS2/setVal": "АРСН.2 S2",
              "LD0/SetACHR_GGIO2/ARSNT/setVal": "АРСН.2 Т",
              "LD0/SetACHR_GGIO2/ARSNTimp/setVal": "АРСН.2 Тимп",
              "LD0/SetACHR_GGIO2/ARSNU/setMag/f": "АРСН.2 U",
              "LD0/SetACHR_GGIO2/ARSNU2/setMag/f": "АРСН.2 U2",
              "LD0/SetACHR_GGIO3/ACHR1F/setMag/f": "АЧР-1.3 F",
              "LD0/SetACHR_GGIO3/ACHR1S1/setVal": "АЧР-1.3 S1",
              "LD0/SetACHR_GGIO3/ACHR1S2/setVal": "АЧР-1.3 S2",
              "LD0/SetACHR_GGIO3/ACHR1T/setVal": "АЧР-1.3 Т",
              "LD0/SetACHR_GGIO3/ACHR1dFdt/setMag/f": "АЧР-1.3 dF/dt",
              "LD0/SetACHR_GGIO3/ACHR2Fp/setMag/f": "АЧР-2.3 F(п)",
              "LD0/SetACHR_GGIO3/ACHR2Fv/setMag/f": "АЧР-2.3 F(в)",
              "LD0/SetACHR_GGIO3/ACHR2S1/setVal": "АЧР-2.3 S1",
              "LD0/SetACHR_GGIO3/ACHR2S2/setVal": "АЧР-2.3 S2",
              "LD0/SetACHR_GGIO3/ACHR2Tf/setVal": "АЧР-2.3 Тf",
              "LD0/SetACHR_GGIO3/ACHR2Tu/setVal": "АЧР-2.3 Тu",
              "LD0/SetACHR_GGIO3/ACHR2U/setMag/f": "АЧР-2.3 U",
              "LD0/SetACHR_GGIO3/ACHRCF/setMag/f": "АЧР-С.3 F",
              "LD0/SetACHR_GGIO3/ACHRCS1/setVal": "АЧР-С.3 S1",
              "LD0/SetACHR_GGIO3/ACHRCdFdt/setMag/f": "АЧР-С.3 dF/dt",
              "LD0/SetACHR_GGIO3/ACHRTimp/setVal": "АЧР.3 Тимп",
              "LD0/SetACHR_GGIO3/ARSNS1/setVal": "АРСН.3 S1",
              "LD0/SetACHR_GGIO3/ARSNS2/setVal": "АРСН.3 S2",
              "LD0/SetACHR_GGIO3/ARSNT/setVal": "АРСН.3 Т",
              "LD0/SetACHR_GGIO3/ARSNTimp/setVal": "АРСН.3 Тимп",
              "LD0/SetACHR_GGIO3/ARSNU/setMag/f": "АРСН.3 U",
              "LD0/SetACHR_GGIO3/ARSNU2/setMag/f": "АРСН.3 U2",
              "LD0/SetAPV_GGIO1/APVS1/setVal": "АПВ.1 S1",
              "LD0/SetAPV_GGIO1/APVS2/setVal": "АПВ.1 S2",
              "LD0/SetAPV_GGIO1/APVT1c/setVal": "АПВ.1 Т1ц",
              "LD0/SetAPV_GGIO1/APVT2c/setVal": "АПВ.1 Т2ц",
              "LD0/SetAPV_GGIO1/APVTgot/setVal": "АПВ.1 Тгот",
              "LD0/SetAPV_GGIO2/APVS1/setVal": "АПВ.2 S1",
              "LD0/SetAPV_GGIO2/APVS2/setVal": "АПВ.2 S2",
              "LD0/SetAPV_GGIO2/APVT1c/setVal": "АПВ.2 Т1ц",
              "LD0/SetAPV_GGIO2/APVT2c/setVal": "АПВ.2 Т2ц",
              "LD0/SetAPV_GGIO2/APVTgot/setVal": "АПВ.2 Тгот",
              "LD0/SetAVR_GGIO1/AVRF/setMag/f": "АВР F",
              "LD0/SetAVR_GGIO1/AVRS1/setVal": "АВР S1",
              "LD0/SetAVR_GGIO1/AVRS2/setVal": "АВР S2",
              "LD0/SetAVR_GGIO1/AVRS3/setVal": "АВР S3",
              "LD0/SetAVR_GGIO1/AVRS4/setVal": "АВР S4",
              "LD0/SetAVR_GGIO1/AVRS5/setVal": "АВР S5",
              "LD0/SetAVR_GGIO1/AVRS6/setVal": "АВР S6",
              "LD0/SetAVR_GGIO1/AVRS7/setVal": "АВР S7",
              "LD0/SetAVR_GGIO1/AVRT/setVal": "АВР Т",
              "LD0/SetAVR_GGIO1/AVRTvn/setVal": "АВР Твнеш",
              "LD0/SetAVR_GGIO1/AVRTzpp/setVal": "АВР Тзпп",
              "LD0/SetAVR_GGIO1/AVRTzppsv/setVal": "АВР Тзпп.св",
              "LD0/SetAVR_GGIO1/AVRU/setMag/f": "АВР U",
              "LD0/SetAVR_GGIO1/AVRU2/setMag/f": "АВР U2",
              "LD0/SetAVR_GGIO1/AVRUtn2/setMag/f": "АВР Uтн2",
              "LD0/SetCHAPV_GGIO1/APVNS1/setVal": "АПВН.1 S1",
              "LD0/SetCHAPV_GGIO1/APVNT/setVal": "АПВН.1 Т",
              "LD0/SetCHAPV_GGIO1/APVNTcontr/setVal": "АПВН.1 Тконтр",
              "LD0/SetCHAPV_GGIO1/APVNTgot/setVal": "АПВН.1 Тгот",
              "LD0/SetCHAPV_GGIO1/APVNTimp/setVal": "АПВН.1 Тимп",
              "LD0/SetCHAPV_GGIO1/APVNU/setMag/f": "АПВН.1 U",
              "LD0/SetCHAPV_GGIO1/CHAPVF/setMag/f": "ЧАПВ.1 F",
              "LD0/SetCHAPV_GGIO1/CHAPVS1/setVal": "ЧАПВ.1 S1",
              "LD0/SetCHAPV_GGIO1/CHAPVS2/setVal": "ЧАПВ.1 S2",
              "LD0/SetCHAPV_GGIO1/CHAPVT/setVal": "ЧАПВ.1 Т",
              "LD0/SetCHAPV_GGIO1/CHAPVTgot/setVal": "ЧАПВ.1 Тгот",
              "LD0/SetCHAPV_GGIO1/CHAPVTimp/setVal": "ЧАПВ.1 Тимп",
              "LD0/SetCHAPV_GGIO1/CHAPVU/setMag/f": "ЧАПВ.1 U",
              "LD0/SetCHAPV_GGIO2/APVNS1/setVal": "АПВН.2 S1",
              "LD0/SetCHAPV_GGIO2/APVNT/setVal": "АПВН.2 Т",
              "LD0/SetCHAPV_GGIO2/APVNTcontr/setVal": "АПВН.2 Тконтр",
              "LD0/SetCHAPV_GGIO2/APVNTgot/setVal": "АПВН.2 Тгот",
              "LD0/SetCHAPV_GGIO2/APVNTimp/setVal": "АПВН.2 Тимп",
              "LD0/SetCHAPV_GGIO2/APVNU/setMag/f": "АПВН.2 U",
              "LD0/SetCHAPV_GGIO2/CHAPVF/setMag/f": "ЧАПВ.2 F",
              "LD0/SetCHAPV_GGIO2/CHAPVS1/setVal": "ЧАПВ.2 S1",
              "LD0/SetCHAPV_GGIO2/CHAPVS2/setVal": "ЧАПВ.2 S2",
              "LD0/SetCHAPV_GGIO2/CHAPVT/setVal": "ЧАПВ.2 Т",
              "LD0/SetCHAPV_GGIO2/CHAPVTgot/setVal": "ЧАПВ.2 Тгот",
              "LD0/SetCHAPV_GGIO2/CHAPVTimp/setVal": "ЧАПВ.2 Тимп",
              "LD0/SetCHAPV_GGIO2/CHAPVU/setMag/f": "ЧАПВ.2 U",
              "LD0/SetCHAPV_GGIO3/APVNS1/setVal": "АПВН.3 S1",
              "LD0/SetCHAPV_GGIO3/APVNT/setVal": "АПВН.3 Т",
              "LD0/SetCHAPV_GGIO3/APVNTcontr/setVal": "АПВН.3 Тконтр",
              "LD0/SetCHAPV_GGIO3/APVNTgot/setVal": "АПВН.3 Тгот",
              "LD0/SetCHAPV_GGIO3/APVNTimp/setVal": "АПВН.3 Тимп",
              "LD0/SetCHAPV_GGIO3/APVNU/setMag/f": "АПВН.3 U",
              "LD0/SetCHAPV_GGIO3/CHAPVF/setMag/f": "ЧАПВ.3 F",
              "LD0/SetCHAPV_GGIO3/CHAPVS1/setVal": "ЧАПВ.3 S1",
              "LD0/SetCHAPV_GGIO3/CHAPVS2/setVal": "ЧАПВ.3 S2",
              "LD0/SetCHAPV_GGIO3/CHAPVT/setVal": "ЧАПВ.3 Т",
              "LD0/SetCHAPV_GGIO3/CHAPVTgot/setVal": "ЧАПВ.3 Тгот",
              "LD0/SetCHAPV_GGIO3/CHAPVTimp/setVal": "ЧАПВ.3 Тимп",
              "LD0/SetCHAPV_GGIO3/CHAPVU/setMag/f": "ЧАПВ.3 U",
              "LD0/SetDGZ_GGIO1/DGZ3U0/setMag/f": "ДгЗ 3U0",
              "LD0/SetDGZ_GGIO1/DGZI/setMag/f": "ДгЗ I",
              "LD0/SetDGZ_GGIO1/DGZS1/setVal": "ДгЗ S1",
              "LD0/SetDGZ_GGIO1/DGZS2/setVal": "ДгЗ S2",
              "LD0/SetDGZ_GGIO1/DGZS3/setVal": "ДгЗ S3",
              "LD0/SetDGZ_GGIO1/DGZS4/setVal": "ДгЗ S4",
              "LD0/SetDGZ_GGIO1/DGZU/setMag/f": "ДгЗ U",
              "LD0/SetDIAG_GGIO1/DIAGS1/setVal": "ДИАГ S1",
              "LD0/SetDIAG_GGIO1/DIAGS2/setVal": "ДИАГ S2",
              "LD0/SetDIAG_GGIO1/DIAGS3/setVal": "ДИАГ S3",
              "LD0/SetDIAG_GGIO1/DIAGS4/setVal": "ДИАГ S4",
              "LD0/SetDIAG_GGIO1/DIAGTotkl/setVal": "ДИАГ Тоткл",
              "LD0/SetDIAG_GGIO1/DIAGTprug/setVal": "ДИАГ Тпруж",
              "LD0/SetDIAG_GGIO1/DIAGTrporpv/setVal": "ДИАГ Трпо.рпв",
              "LD0/SetDIAG_GGIO1/DIAGTvkl/setVal": "ДИАГ Твкл",
              "LD0/SetDZDV_GGIO1/DZDV1Ksm/setMag/f": "ДЗДВ.1 Kсм",
              "LD0/SetDZDV_GGIO1/DZDV1Nhar/setVal": "ДЗДВ.1 Nхар.",
              "LD0/SetDZDV_GGIO1/DZDV1Phi/setMag/f": "ДЗДВ.1 Ф",
              "LD0/SetDZDV_GGIO1/DZDV1Phi1/setMag/f": "ДЗДВ.1 Ф1",
              "LD0/SetDZDV_GGIO1/DZDV1Phi2/setMag/f": "ДЗДВ.1 Ф2",
              "LD0/SetDZDV_GGIO1/DZDV1Rsr/setMag/f": "ДЗДВ.1 Rср",
              "LD0/SetDZDV_GGIO1/DZDV1S1/setVal": "ДЗДВ.1 S1",
              "LD0/SetDZDV_GGIO1/DZDV1S2/setVal": "ДЗДВ.1 S2",
              "LD0/SetDZDV_GGIO1/DZDV1S3/setVal": "ДЗДВ.1 S3",
              "LD0/SetDZDV_GGIO1/DZDV1TA0/setVal": "ДЗДВ.1 ТA0",
              "LD0/SetDZDV_GGIO1/DZDV1TB0/setVal": "ДЗДВ.1 ТB0",
              "LD0/SetDZDV_GGIO1/DZDV1TC0/setVal": "ДЗДВ.1 ТC0",
              "LD0/SetDZDV_GGIO1/DZDV1Zsm/setMag/f": "ДЗДВ.1 Zсм",
              "LD0/SetDZDV_GGIO1/DZDV1Zsr/setMag/f": "ДЗДВ.1 Zср",
              "LD0/SetDZDV_GGIO1/DZDV2Ksm/setMag/f": "ДЗДВ.2 Kсм",
              "LD0/SetDZDV_GGIO1/DZDV2Nhar/setVal": "ДЗДВ.2 Nхар.",
              "LD0/SetDZDV_GGIO1/DZDV2Phi/setMag/f": "ДЗДВ.2 Ф",
              "LD0/SetDZDV_GGIO1/DZDV2Phi1/setMag/f": "ДЗДВ.2 Ф1",
              "LD0/SetDZDV_GGIO1/DZDV2Phi2/setMag/f": "ДЗДВ.2 Ф2",
              "LD0/SetDZDV_GGIO1/DZDV2Rsr/setMag/f": "ДЗДВ.2 Rср",
              "LD0/SetDZDV_GGIO1/DZDV2S1/setVal": "ДЗДВ.2 S1",
              "LD0/SetDZDV_GGIO1/DZDV2S2/setVal": "ДЗДВ.2 S2",
              "LD0/SetDZDV_GGIO1/DZDV2S3/setVal": "ДЗДВ.2 S3",
              "LD0/SetDZDV_GGIO1/DZDV2TA0/setVal": "ДЗДВ.2 ТA0",
              "LD0/SetDZDV_GGIO1/DZDV2TB0/setVal": "ДЗДВ.2 ТB0",
              "LD0/SetDZDV_GGIO1/DZDV2TC0/setVal": "ДЗДВ.2 ТC0",
              "LD0/SetDZDV_GGIO1/DZDV2Zsm/setMag/f": "ДЗДВ.2 Zсм",
              "LD0/SetDZDV_GGIO1/DZDV2Zsr/setMag/f": "ДЗДВ.2 Zср",
              "LD0/SetDZDV_GGIO1/DZDV3I0/setMag/f": "ДЗДВ 3I0",
              "LD0/SetDZDV_GGIO1/DZDV3Ksm/setMag/f": "ДЗДВ.3 Kсм",
              "LD0/SetDZDV_GGIO1/DZDV3Nhar/setVal": "ДЗДВ.3 Nхар.",
              "LD0/SetDZDV_GGIO1/DZDV3Phi/setMag/f": "ДЗДВ.3 Ф",
              "LD0/SetDZDV_GGIO1/DZDV3Phi1/setMag/f": "ДЗДВ.3 Ф1",
              "LD0/SetDZDV_GGIO1/DZDV3Phi2/setMag/f": "ДЗДВ.3 Ф2",
              "LD0/SetDZDV_GGIO1/DZDV3Rsr/setMag/f": "ДЗДВ.3 Rср",
              "LD0/SetDZDV_GGIO1/DZDV3S1/setVal": "ДЗДВ.3 S1",
              "LD0/SetDZDV_GGIO1/DZDV3S2/setVal": "ДЗДВ.3 S2",
              "LD0/SetDZDV_GGIO1/DZDV3S3/setVal": "ДЗДВ.3 S3",
              "LD0/SetDZDV_GGIO1/DZDV3TA0/setVal": "ДЗДВ.3 ТA0",
              "LD0/SetDZDV_GGIO1/DZDV3TB0/setVal": "ДЗДВ.3 ТB0",
              "LD0/SetDZDV_GGIO1/DZDV3TC0/setVal": "ДЗДВ.3 ТC0",
              "LD0/SetDZDV_GGIO1/DZDV3Zsm/setMag/f": "ДЗДВ.3 Zсм",
              "LD0/SetDZDV_GGIO1/DZDV3Zsr/setMag/f": "ДЗДВ.3 Zср",
              "LD0/SetDZDV_GGIO1/DZDVKkomp/setMag/f": "ДЗДВ Kкомп",
              "LD0/SetDZDV_GGIO1/DZDVPhin/setMag/f": "ДЗДВ Фн",
              "LD0/SetDZDV_GGIO1/DZDVRn/setMag/f": "ДЗДВ Rн",
              "LD0/SetDZDV_GGIO1/DZDVS1/setVal": "ДЗДВ S1",
              "LD0/SetDZDV_GGIO1/DZDVd1Ksm/setMag/f": "ДЗДВд.1 Kсм",
              "LD0/SetDZDV_GGIO1/DZDVd1Phi/setMag/f": "ДЗДВд.1 Ф",
              "LD0/SetDZDV_GGIO1/DZDVd1Phi1/setMag/f": "ДЗДВд.1 Ф1",
              "LD0/SetDZDV_GGIO1/DZDVd1Phi2/setMag/f": "ДЗДВд.1 Ф2",
              "LD0/SetDZDV_GGIO1/DZDVd1Rsr/setMag/f": "ДЗДВд.1 Rср",
              "LD0/SetDZDV_GGIO1/DZDVd1S1/setVal": "ДЗДВд.1 S1",
              "LD0/SetDZDV_GGIO1/DZDVd1Zsm/setMag/f": "ДЗДВд.1 Zсм",
              "LD0/SetDZDV_GGIO1/DZDVd1Zsr/setMag/f": "ДЗДВд.1 Zср",
              "LD0/SetDZDV_GGIO1/DZDVd2Ksm/setMag/f": "ДЗДВд.2 Kсм",
              "LD0/SetDZDV_GGIO1/DZDVd2Phi/setMag/f": "ДЗДВд.2 Ф",
              "LD0/SetDZDV_GGIO1/DZDVd2Phi1/setMag/f": "ДЗДВд.2 Ф1",
              "LD0/SetDZDV_GGIO1/DZDVd2Phi2/setMag/f": "ДЗДВд.2 Ф2",
              "LD0/SetDZDV_GGIO1/DZDVd2Rsr/setMag/f": "ДЗДВд.2 Rср",
              "LD0/SetDZDV_GGIO1/DZDVd2S1/setVal": "ДЗДВд.2 S1",
              "LD0/SetDZDV_GGIO1/DZDVd2Zsm/setMag/f": "ДЗДВд.2 Zсм",
              "LD0/SetDZDV_GGIO1/DZDVd2Zsr/setMag/f": "ДЗДВд.2 Zср",
              "LD0/SetDZDV_GGIO1/DZDVd3Ksm/setMag/f": "ДЗДВд.3 Kсм",
              "LD0/SetDZDV_GGIO1/DZDVd3Phi/setMag/f": "ДЗДВд.3 Ф",
              "LD0/SetDZDV_GGIO1/DZDVd3Phi1/setMag/f": "ДЗДВд.3 Ф1",
              "LD0/SetDZDV_GGIO1/DZDVd3Phi2/setMag/f": "ДЗДВд.3 Ф2",
              "LD0/SetDZDV_GGIO1/DZDVd3Rsr/setMag/f": "ДЗДВд.3 Rср",
              "LD0/SetDZDV_GGIO1/DZDVd3S1/setVal": "ДЗДВд.3 S1",
              "LD0/SetDZDV_GGIO1/DZDVd3Zsm/setMag/f": "ДЗДВд.3 Zсм",
              "LD0/SetDZDV_GGIO1/DZDVd3Zsr/setMag/f": "ДЗДВд.3 Zср",
              "LD0/SetDZMF_GGIO1/DZMF1Ksm/setMag/f": "ДЗМФ.1 Kсм",
              "LD0/SetDZMF_GGIO1/DZMF1Nhar/setVal": "ДЗМФ.1 Nхар.",
              "LD0/SetDZMF_GGIO1/DZMF1Phi/setMag/f": "ДЗМФ.1 Ф",
              "LD0/SetDZMF_GGIO1/DZMF1Phi1/setMag/f": "ДЗМФ.1 Ф1",
              "LD0/SetDZMF_GGIO1/DZMF1Phi2/setMag/f": "ДЗМФ.1 Ф2",
              "LD0/SetDZMF_GGIO1/DZMF1Rsr/setMag/f": "ДЗМФ.1 Rср",
              "LD0/SetDZMF_GGIO1/DZMF1S1/setVal": "ДЗМФ.1 S1",
              "LD0/SetDZMF_GGIO1/DZMF1S2/setVal": "ДЗМФ.1 S2",
              "LD0/SetDZMF_GGIO1/DZMF1S3/setVal": "ДЗМФ.1 S3",
              "LD0/SetDZMF_GGIO1/DZMF1S4/setVal": "ДЗМФ.1 S4",
              "LD0/SetDZMF_GGIO1/DZMF1S5/setVal": "ДЗМФ.1 S5",
              "LD0/SetDZMF_GGIO1/DZMF1T/setVal": "ДЗМФ.1 Т",
              "LD0/SetDZMF_GGIO1/DZMF1Zsm/setMag/f": "ДЗМФ.1 Zсм",
              "LD0/SetDZMF_GGIO1/DZMF1Zsr/setMag/f": "ДЗМФ.1 Zср",
              "LD0/SetDZMF_GGIO1/DZMF2Ksm/setMag/f": "ДЗМФ.2 Kсм",
              "LD0/SetDZMF_GGIO1/DZMF2Nhar/setVal": "ДЗМФ.2 Nхар.",
              "LD0/SetDZMF_GGIO1/DZMF2Phi/setMag/f": "ДЗМФ.2 Ф",
              "LD0/SetDZMF_GGIO1/DZMF2Phi1/setMag/f": "ДЗМФ.2 Ф1",
              "LD0/SetDZMF_GGIO1/DZMF2Phi2/setMag/f": "ДЗМФ.2 Ф2",
              "LD0/SetDZMF_GGIO1/DZMF2Rsr/setMag/f": "ДЗМФ.2 Rср",
              "LD0/SetDZMF_GGIO1/DZMF2S1/setVal": "ДЗМФ.2 S1",
              "LD0/SetDZMF_GGIO1/DZMF2S2/setVal": "ДЗМФ.2 S2",
              "LD0/SetDZMF_GGIO1/DZMF2S3/setVal": "ДЗМФ.2 S3",
              "LD0/SetDZMF_GGIO1/DZMF2S4/setVal": "ДЗМФ.2 S4",
              "LD0/SetDZMF_GGIO1/DZMF2S5/setVal": "ДЗМФ.2 S5",
              "LD0/SetDZMF_GGIO1/DZMF2T/setVal": "ДЗМФ.2 Т",
              "LD0/SetDZMF_GGIO1/DZMF2Zsm/setMag/f": "ДЗМФ.2 Zсм",
              "LD0/SetDZMF_GGIO1/DZMF2Zsr/setMag/f": "ДЗМФ.2 Zср",
              "LD0/SetDZMF_GGIO1/DZMF3Ksm/setMag/f": "ДЗМФ.3 Kсм",
              "LD0/SetDZMF_GGIO1/DZMF3Nhar/setVal": "ДЗМФ.3 Nхар.",
              "LD0/SetDZMF_GGIO1/DZMF3Phi/setMag/f": "ДЗМФ.3 Ф",
              "LD0/SetDZMF_GGIO1/DZMF3Phi1/setMag/f": "ДЗМФ.3 Ф1",
              "LD0/SetDZMF_GGIO1/DZMF3Phi2/setMag/f": "ДЗМФ.3 Ф2",
              "LD0/SetDZMF_GGIO1/DZMF3Rsr/setMag/f": "ДЗМФ.3 Rср",
              "LD0/SetDZMF_GGIO1/DZMF3S1/setVal": "ДЗМФ.3 S1",
              "LD0/SetDZMF_GGIO1/DZMF3S2/setVal": "ДЗМФ.3 S2",
              "LD0/SetDZMF_GGIO1/DZMF3S3/setVal": "ДЗМФ.3 S3",
              "LD0/SetDZMF_GGIO1/DZMF3S4/setVal": "ДЗМФ.3 S4",
              "LD0/SetDZMF_GGIO1/DZMF3T/setVal": "ДЗМФ.3 Т",
              "LD0/SetDZMF_GGIO1/DZMF3Zsm/setMag/f": "ДЗМФ.3 Zсм",
              "LD0/SetDZMF_GGIO1/DZMF3Zsr/setMag/f": "ДЗМФ.3 Zср",
              "LD0/SetDZMF_GGIO1/DZMFPhin/setMag/f": "ДЗМФ Фн",
              "LD0/SetDZMF_GGIO1/DZMFRn/setMag/f": "ДЗМФ Rн",
              "LD0/SetDZMF_GGIO1/DZMFS1/setVal": "ДЗМФ S1",
              "LD0/SetDZMF_GGIO1/DZMFd1Ksm/setMag/f": "ДЗМФд.1 Kсм",
              "LD0/SetDZMF_GGIO1/DZMFd1Phi/setMag/f": "ДЗМФд.1 Ф",
              "LD0/SetDZMF_GGIO1/DZMFd1Phi1/setMag/f": "ДЗМФд.1 Ф1",
              "LD0/SetDZMF_GGIO1/DZMFd1Phi2/setMag/f": "ДЗМФд.1 Ф2",
              "LD0/SetDZMF_GGIO1/DZMFd1Rsr/setMag/f": "ДЗМФд.1 Rср",
              "LD0/SetDZMF_GGIO1/DZMFd1S1/setVal": "ДЗМФд.1 S1",
              "LD0/SetDZMF_GGIO1/DZMFd1Zsm/setMag/f": "ДЗМФд.1 Zсм",
              "LD0/SetDZMF_GGIO1/DZMFd1Zsr/setMag/f": "ДЗМФд.1 Zср",
              "LD0/SetDZMF_GGIO1/DZMFd2Ksm/setMag/f": "ДЗМФд.2 Kсм",
              "LD0/SetDZMF_GGIO1/DZMFd2Phi/setMag/f": "ДЗМФд.2 Ф",
              "LD0/SetDZMF_GGIO1/DZMFd2Phi1/setMag/f": "ДЗМФд.2 Ф1",
              "LD0/SetDZMF_GGIO1/DZMFd2Phi2/setMag/f": "ДЗМФд.2 Ф2",
              "LD0/SetDZMF_GGIO1/DZMFd2Rsr/setMag/f": "ДЗМФд.2 Rср",
              "LD0/SetDZMF_GGIO1/DZMFd2S1/setVal": "ДЗМФд.2 S1",
              "LD0/SetDZMF_GGIO1/DZMFd2Zsm/setMag/f": "ДЗМФд.2 Zсм",
              "LD0/SetDZMF_GGIO1/DZMFd2Zsr/setMag/f": "ДЗМФд.2 Zср",
              "LD0/SetDZMF_GGIO1/DZMFd3Ksm/setMag/f": "ДЗМФд.3 Kсм",
              "LD0/SetDZMF_GGIO1/DZMFd3Phi/setMag/f": "ДЗМФд.3 Ф",
              "LD0/SetDZMF_GGIO1/DZMFd3Phi1/setMag/f": "ДЗМФд.3 Ф1",
              "LD0/SetDZMF_GGIO1/DZMFd3Phi2/setMag/f": "ДЗМФд.3 Ф2",
              "LD0/SetDZMF_GGIO1/DZMFd3Rsr/setMag/f": "ДЗМФд.3 Rср",
              "LD0/SetDZMF_GGIO1/DZMFd3S1/setVal": "ДЗМФд.3 S1",
              "LD0/SetDZMF_GGIO1/DZMFd3Zsm/setMag/f": "ДЗМФд.3 Zсм",
              "LD0/SetDZMF_GGIO1/DZMFd3Zsr/setMag/f": "ДЗМФд.3 Zср",
              "LD0/SetKCN_GGIO1/KCNS1/setVal": "КЦН S1",
              "LD0/SetKCN_GGIO1/KCNS2/setVal": "КЦН S2",
              "LD0/SetKCN_GGIO1/KCNS4/setVal": "КЦН S4",
              "LD0/SetKCN_GGIO1/KCNT1/setVal": "КЦН Т1",
              "LD0/SetKCN_GGIO1/KCNT2/setVal": "КЦН Т2",
              "LD0/SetKCT_GGIO1/KCTb3I0/setMag/f": "КЦТб 3I0",
              "LD0/SetKCT_GGIO1/KCTb3I0r/setMag/f": "КЦТб 3I0р",
              "LD0/SetKCT_GGIO1/KCTbImax/setMag/f": "КЦТб Iмакс",
              "LD0/SetKCT_GGIO1/KCTbS1/setVal": "КЦТб S1",
              "LD0/SetKCT_GGIO1/KCTmImax/setMag/f": "КЦТм Iмакс",
              "LD0/SetKCT_GGIO1/KCTmImin/setMag/f": "КЦТм Iмин",
              "LD0/SetKCT_GGIO1/KCTmS1/setVal": "КЦТм S1",
              "LD0/SetKCT_GGIO1/KCTmT/setVal": "КЦТм Т",
              "LD0/SetKM_GGIO1/KM1Phi/setMag/f": "КМ.1 Ф",
              "LD0/SetKM_GGIO1/KM1S/setMag/f": "КМ.1 S",
              "LD0/SetKM_GGIO1/KM1S1/setVal": "КМ.1 S1",
              "LD0/SetKM_GGIO1/KM1S2/setVal": "КМ.1 S2",
              "LD0/SetKM_GGIO1/KM1S3/setVal": "КМ.1 S3",
              "LD0/SetKM_GGIO1/KM1T/setVal": "КМ.1 Т",
              "LD0/SetKM_GGIO1/KM1Tv/setVal": "КМ.1 Тв",
              "LD0/SetKM_GGIO1/KM2Phi/setMag/f": "КМ.2 Ф",
              "LD0/SetKM_GGIO1/KM2S/setMag/f": "КМ.2 S",
              "LD0/SetKM_GGIO1/KM2S1/setVal": "КМ.2 S1",
              "LD0/SetKM_GGIO1/KM2S2/setVal": "КМ.2 S2",
              "LD0/SetKM_GGIO1/KM2S3/setVal": "КМ.2 S3",
              "LD0/SetKM_GGIO1/KM2T/setVal": "КМ.2 Т",
              "LD0/SetKM_GGIO1/KM2Tv/setVal": "КМ.2 Тв",
              "LD0/SetKM_GGIO1/KMUmin/setMag/f": "КМ Uмин",
              "LD0/SetKM_GGIO1/KMfazaIf/setVal": "КМ Фаза Iф",
              "LD0/SetKN_GGIO1/KNTN13U0/setMag/f": "КН ТН1 3U0",
              "LD0/SetKN_GGIO1/KNTN1S1/setVal": "КН ТН1 S1",
              "LD0/SetKN_GGIO1/KNTN1S2/setVal": "КН ТН1 S2",
              "LD0/SetKN_GGIO1/KNTN1S3/setVal": "КН ТН1 S3",
              "LD0/SetKN_GGIO1/KNTN1U2/setMag/f": "КН ТН1 U2",
              "LD0/SetKN_GGIO1/KNTN1Ul/setMag/f": "КН ТН1 U<",
              "LD0/SetKN_GGIO1/KNTN1Um/setMag/f": "КН ТН1 U>",
              "LD0/SetKN_GGIO1/KNTN2S1/setVal": "КН ТН2 S1",
              "LD0/SetKN_GGIO1/KNTN2Ul/setMag/f": "КН ТН2 U<",
              "LD0/SetKN_GGIO1/KNTN2Um/setMag/f": "КН ТН2 U>",
              "LD0/SetKN_GGIO1/VklKNS1/setVal": "ВклКН S1",
              "LD0/SetKN_GGIO1/VklKNS2/setVal": "ВклКН S2",
              "LD0/SetKN_GGIO1/VklKNS3/setVal": "ВклКН S3",
              "LD0/SetKN_GGIO1/VklKNT/setVal": "ВклКН Т",
              "LD0/SetLZSH_GGIO1/LZSHI/setMag/f": "ЛЗШ I",
              "LD0/SetLZSH_GGIO1/LZSHS1/setVal": "ЛЗШ S1",
              "LD0/SetLZSH_GGIO1/LZSHS2/setVal": "ЛЗШ S2",
              "LD0/SetLZSH_GGIO1/LZSHS3/setVal": "ЛЗШ S3",
              "LD0/SetLZSH_GGIO1/LZSHT/setVal": "ЛЗШ Т",
              "LD0/SetLZSH_GGIO1/LZSHU/setMag/f": "ЛЗШ U",
              "LD0/SetLZSH_GGIO1/LZSHU2/setMag/f": "ЛЗШ U2",
              "LD0/SetMTZ_GGIO1/MTZ1I/setMag/f": "МТЗ.1 I",
              "LD0/SetMTZ_GGIO1/MTZ1K/setMag/f": "МТЗ.1 K",
              "LD0/SetMTZ_GGIO1/MTZ1Nhar/setVal": "МТЗ.1 Nхар.",
              "LD0/SetMTZ_GGIO1/MTZ1S1/setVal": "МТЗ.1 S1",
              "LD0/SetMTZ_GGIO1/MTZ1S2/setVal": "МТЗ.1 S2",
              "LD0/SetMTZ_GGIO1/MTZ1S3/setVal": "МТЗ.1 S3",
              "LD0/SetMTZ_GGIO1/MTZ1S4/setVal": "МТЗ.1 S4",
              "LD0/SetMTZ_GGIO1/MTZ1T/setVal": "МТЗ.1 Т",
              "LD0/SetMTZ_GGIO1/MTZ1U/setMag/f": "МТЗ.1 U",
              "LD0/SetMTZ_GGIO1/MTZ1U2/setMag/f": "МТЗ.1 U2",
              "LD0/SetMTZ_GGIO1/MTZ2I/setMag/f": "МТЗ.2 I",
              "LD0/SetMTZ_GGIO1/MTZ2S1/setVal": "МТЗ.2 S1",
              "LD0/SetMTZ_GGIO1/MTZ2T/setVal": "МТЗ.2 Т",
              "LD0/SetMTZ_GGIO1/MTZ3I/setMag/f": "МТЗ.3 I",
              "LD0/SetMTZ_GGIO1/MTZ3S1/setVal": "МТЗ.3 S1",
              "LD0/SetMTZ_GGIO1/MTZ3S2/setVal": "МТЗ.3 S2",
              "LD0/SetMTZ_GGIO1/MTZ3S3/setVal": "МТЗ.3 S3",
              "LD0/SetMTZ_GGIO1/MTZ3T/setVal": "МТЗ.3 Т",
              "LD0/SetMTZ_GGIO1/MTZ3U/setMag/f": "МТЗ.3 U",
              "LD0/SetMTZ_GGIO1/MTZ3U2/setMag/f": "МТЗ.3 U2",
              "LD0/SetMTZ_GGIO1/RNMPhiMCh/setMag/f": "РНМ Фмч",
              "LD0/SetOSC_GGIO1/OSCS1/setVal": "ОСЦ S1",
              "LD0/SetOSC_GGIO1/OSCTblok/setVal": "ОСЦ Тблок",
              "LD0/SetOSC_GGIO1/OSCTmax/setVal": "ОСЦ Тмакс",
              "LD0/SetOSC_GGIO1/OSCTpost/setVal": "ОСЦ Тпост",
              "LD0/SetOSC_GGIO1/OSCTpred/setVal": "ОСЦ Тпред",
              "LD0/SetOTHER_GGIO1/AUVS1/setVal": "АУВ S1",
              "LD0/SetOTHER_GGIO1/FAZS1/setVal": "ФАЗ S1",
              "LD0/SetOTHER_GGIO1/OTKLTimp/setVal": "ОТКЛ Тимп",
              "LD0/SetOTHER_GGIO1/OTKLTotkl/setVal": "ОТКЛ Тоткл",
              "LD0/SetOTHER_GGIO1/OUS1/setVal": "ОУ S1",
              "LD0/SetOTHER_GGIO1/OUS2/setVal": "ОУ S2",
              "LD0/SetOTHER_GGIO1/OUS3/setVal": "ОУ S3",
              "LD0/SetOTHER_GGIO1/PROGRTvoz/setVal": "ПРОГР Твоз",
              "LD0/SetOTHER_GGIO1/TIS1/setVal": "ТИ S1",
              "LD0/SetOTHER_GGIO1/TITdec/setVal": "ТИ Тдец",
              "LD0/SetOTHER_GGIO1/TITf/setVal": "ТИ Тф",
              "LD0/SetOTHER_GGIO1/TTS1/setVal": "ТТ S1",
              "LD0/SetOTHER_GGIO1/VIKLS1/setVal": "ВЫКЛ S1",
              "LD0/SetOTHER_GGIO1/VKLTimp/setVal": "ВКЛ Тимп",
              "LD0/SetOTHER_GGIO1/ZashEMT/setVal": "Защ.ЭМ Т",
              "LD0/SetRAVR_GGIO1/RAVRF/setMag/f": "РАВР F",
              "LD0/SetRAVR_GGIO1/RAVRS1/setVal": "РАВР S1",
              "LD0/SetRAVR_GGIO1/RAVRS2/setVal": "РАВР S2",
              "LD0/SetRAVR_GGIO1/RAVRS3/setVal": "РАВР S3",
              "LD0/SetRAVR_GGIO1/RAVRU/setMag/f": "РАВР U",
              "LD0/SetRAVR_GGIO1/RAVRU2/setMag/f": "РАВР U2",
              "LD0/SetRAVR_GGIO1/RAVRUtn2/setMag/f": "РАВР Uтн2",
              "LD0/SetRES_GGIO1/KRINom/setVal": "КР Iном",
              "LD0/SetRES_GGIO1/KRIoNom/setVal": "КР Iо.ном",
              "LD0/SetRES_GGIO1/MR/setVal": "МР",
              "LD0/SetRES_GGIO1/RESINom/setMag/f": "РЕС Iном",
              "LD0/SetRES_GGIO1/RESIoNom/setMag/f": "РЕС Iо.ном",
              "LD0/SetRES_GGIO1/RESS1/setVal": "РЕС S1",
              "LD0/SetRES_GGIO1/RESSign/setMag/f": "РЕС сигн.",
              "LD0/SetRES_GGIO1/RESTotkl/setVal": "РЕС Тоткл",
              "LD0/SetRES_GGIO1/RESnachzn/setMag/f": "РЕС нач.зн.",
              "LD0/SetSYN_GGIO1/KSK/setMag/f": "КС K",
              "LD0/SetSYN_GGIO1/KSPhipov/setMag/f": "КС Фпов",
              "LD0/SetSYN_GGIO1/KSS1/setVal": "КС S1",
              "LD0/SetSYN_GGIO1/KSS2/setVal": "КС S2",
              "LD0/SetSYN_GGIO1/KSS3/setVal": "КС S3",
              "LD0/SetSYN_GGIO1/KSS4/setVal": "КС S4",
              "LD0/SetSYN_GGIO1/KSS5/setVal": "КС S5",
              "LD0/SetSYN_GGIO1/KSS6/setVal": "КС S6",
              "LD0/SetSYN_GGIO1/KST/setVal": "КС Т",
              "LD0/SetSYN_GGIO1/KSTvkl/setMag/f": "КС Твкл",
              "LD0/SetSYN_GGIO1/KSU/setMag/f": "КС U",
              "LD0/SetSYN_GGIO1/KSU2/setMag/f": "КС U2",
              "LD0/SetSYN_GGIO1/KSdF/setMag/f": "КС dF",
              "LD0/SetSYN_GGIO1/KSdPhi/setMag/f": "КС dФ",
              "LD0/SetSYN_GGIO1/KSdU/setMag/f": "КС dU",
              "LD0/SetTO_GGIO1/BLK2hI/setMag/f": "БЛК2г I",
              "LD0/SetTO_GGIO1/BLK2hI2hI1h/setMag/f": "БЛК2г I2г/I1г",
              "LD0/SetTO_GGIO1/BLK2hS1/setVal": "БЛК2г S1",
              "LD0/SetTO_GGIO1/BLK2hT/setVal": "БЛК2г Т",
              "LD0/SetTO_GGIO1/TO1I/setMag/f": "ТО.1 I",
              "LD0/SetTO_GGIO1/TO1S1/setVal": "ТО.1 S1",
              "LD0/SetTO_GGIO1/TO1S2/setVal": "ТО.1 S2",
              "LD0/SetTO_GGIO1/TO1S3/setVal": "ТО.1 S3",
              "LD0/SetTO_GGIO1/TO1T/setVal": "ТО.1 Т",
              "LD0/SetTO_GGIO1/TO2I/setMag/f": "ТО.2 I",
              "LD0/SetTO_GGIO1/TO2S1/setVal": "ТО.2 S1",
              "LD0/SetTO_GGIO1/TO2S2/setVal": "ТО.2 S2",
              "LD0/SetTO_GGIO1/TO2S3/setVal": "ТО.2 S3",
              "LD0/SetTO_GGIO1/TO2T/setVal": "ТО.2 Т",
              "LD0/SetUBK_GGIO1/UBKDI/setMag/f": "УБК dI",
              "LD0/SetUBK_GGIO1/UBKDI2/setMag/f": "УБК dI2",
              "LD0/SetUBK_GGIO1/UBKS1/setVal": "УБК S1",
              "LD0/SetUBK_GGIO1/UBKT/setVal": "УБК Т",
              "LD0/SetUDZDV_GGIO1/UDZDVS1/setVal": "УДЗДВ S1",
              "LD0/SetUDZDV_GGIO1/UDZDVT/setVal": "УДЗДВ Т",
              "LD0/SetUDZMF_GGIO1/UDZMFS1/setVal": "УДЗМФ S1",
              "LD0/SetUDZMF_GGIO1/UDZMFT/setVal": "УДЗМФ Т",
              "LD0/SetUMTZ_GGIO1/UMTZS1/setVal": "УМТЗ S1",
              "LD0/SetUMTZ_GGIO1/UMTZT/setVal": "УМТЗ Т",
              "LD0/SetUROV_GGIO1/UROVI/setMag/f": "УРОВ I",
              "LD0/SetUROV_GGIO1/UROVS1/setVal": "УРОВ S1",
              "LD0/SetUROV_GGIO1/UROVS2/setVal": "УРОВ S2",
              "LD0/SetUROV_GGIO1/UROVT/setVal": "УРОВ Т",
              "LD0/SetVNR_GGIO1/VNRS1/setVal": "ВНР S1",
              "LD0/SetVNR_GGIO1/VNRS2/setVal": "ВНР S2",
              "LD0/SetVNR_GGIO1/VNRT/setVal": "ВНР Т",
              "LD0/SetVNR_GGIO1/VNRTozid/setVal": "ВНР Тожид",
              "LD0/SetVNR_GGIO1/VNRU/setMag/f": "ВНР U",
              "LD0/SetVNR_GGIO1/VNRUtn2/setMag/f": "ВНР Uтн2",
              "LD0/SetVYZ_GGIO1/VYZACHR/setVal": "ВЫЗ АЧР сраб.",
              "LD0/SetVYZ_GGIO1/VYZAPVN/setVal": "ВЫЗ АПВН сраб.",
              "LD0/SetVYZ_GGIO1/VYZARSN/setVal": "ВЫЗ АРСН сраб.",
              "LD0/SetVYZ_GGIO1/VYZAVR/setVal": "ВЫЗ АВР сраб.",
              "LD0/SetVYZ_GGIO1/VYZCHAPV/setVal": "ВЫЗ ЧАПВ сраб.",
              "LD0/SetVYZ_GGIO1/VYZDGZneisp/setVal": "ВЫЗ ДгЗ неиспр.",
              "LD0/SetVYZ_GGIO1/VYZDGZsrab/setVal": "ВЫЗ ДгЗ сраб.",
              "LD0/SetVYZ_GGIO1/VYZDZDV1/setVal": "ВЫЗ ДЗДВ.1 сраб.",
              "LD0/SetVYZ_GGIO1/VYZDZDV2/setVal": "ВЫЗ ДЗДВ.2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZDZDV3/setVal": "ВЫЗ ДЗДВ.3 сраб.",
              "LD0/SetVYZ_GGIO1/VYZDZMF1/setVal": "ВЫЗ ДЗМФ.1 сраб.",
              "LD0/SetVYZ_GGIO1/VYZDZMF2/setVal": "ВЫЗ ДЗМФ.2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZDZMF3/setVal": "ВЫЗ ДЗМФ.3 сраб.",
              "LD0/SetVYZ_GGIO1/VYZEO1EV/setVal": "ВЫЗ ЭО1/ЭВ сраб.",
              "LD0/SetVYZ_GGIO1/VYZEO2/setVal": "ВЫЗ ЭО2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZKCT/setVal": "ВЫЗ КЦТ сраб.",
              "LD0/SetVYZ_GGIO1/VYZKM1/setVal": "ВЫЗ КМ.1 сраб.",
              "LD0/SetVYZ_GGIO1/VYZKM2/setVal": "ВЫЗ КМ.2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZLZSHneisp/setVal": "ВЫЗ ЛЗШ неиспр.",
              "LD0/SetVYZ_GGIO1/VYZLZSHsrab/setVal": "ВЫЗ ЛЗШ сраб.",
              "LD0/SetVYZ_GGIO1/VYZMTZ1/setVal": "ВЫЗ МТЗ.1 сраб.",
              "LD0/SetVYZ_GGIO1/VYZMTZ2/setVal": "ВЫЗ МТЗ.2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZMTZ3/setVal": "ВЫЗ МТЗ.3 сраб.",
              "LD0/SetVYZ_GGIO1/VYZSF6Q1/setVal": "ВЫЗ SF6 Q 1 ст.",
              "LD0/SetVYZ_GGIO1/VYZSF6blokup/setVal": "ВЫЗ SF6 блок. упр.",
              "LD0/SetVYZ_GGIO1/VYZSNOZZ/setVal": "ВЫЗ СНОЗЗ сраб.",
              "LD0/SetVYZ_GGIO1/VYZSO/setVal": "ВЫЗ СО сраб.",
              "LD0/SetVYZ_GGIO1/VYZTO1/setVal": "ВЫЗ ТО.1 сраб.",
              "LD0/SetVYZ_GGIO1/VYZTO2/setVal": "ВЫЗ ТО.2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZUDZDV/setVal": "ВЫЗ УДЗДВ сраб.",
              "LD0/SetVYZ_GGIO1/VYZUDZMF/setVal": "ВЫЗ УДЗМФ сраб.",
              "LD0/SetVYZ_GGIO1/VYZUMTZ/setVal": "ВЫЗ УМТЗ сраб.",
              "LD0/SetVYZ_GGIO1/VYZUrov/setVal": "ВЫЗ УРОВ сраб.",
              "LD0/SetVYZ_GGIO1/VYZUrovp/setVal": "ВЫЗ УРОВп",
              "LD0/SetVYZ_GGIO1/VYZZMN1/setVal": "ВЫЗ ЗМН.1 сраб.",
              "LD0/SetVYZ_GGIO1/VYZZMN2/setVal": "ВЫЗ ЗМН.2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZZOF1/setVal": "ВЫЗ ЗОФ.1 сраб.",
              "LD0/SetVYZ_GGIO1/VYZZOF2/setVal": "ВЫЗ ЗОФ.2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZZOZZ1/setVal": "ВЫЗ ЗОЗЗ.1 сраб.",
              "LD0/SetVYZ_GGIO1/VYZZOZZ2/setVal": "ВЫЗ ЗОЗЗ.2 сраб.",
              "LD0/SetVYZ_GGIO1/VYZZPN/setVal": "ВЫЗ ЗПН сраб.",
              "LD0/SetVYZ_GGIO1/VYZZPP/setVal": "ВЫЗ ЗПП сраб.",
              "LD0/SetVYZ_GGIO1/VYZneispTN1/setVal": "ВЫЗ Неиспр. ТН1",
              "LD0/SetVYZ_GGIO1/VYZneispTN2/setVal": "ВЫЗ Неиспр. ТН2",
              "LD0/SetVYZ_GGIO1/VYZneispvikl/setVal": "ВЫЗ Неиспр. выкл.",
              "LD0/SetVYZ_GGIO1/VYZneuspVNR/setVal": "ВЫЗ Неусп. ВНР",
              "LD0/SetVYZ_GGIO1/VYZresvikl/setVal": "ВЫЗ Ресурс",
              "LD0/SetZMN_GGIO1/ZMN1S1/setVal": "ЗМН.1 S1",
              "LD0/SetZMN_GGIO1/ZMN1S2/setVal": "ЗМН.1 S2",
              "LD0/SetZMN_GGIO1/ZMN1S3/setVal": "ЗМН.1 S3",
              "LD0/SetZMN_GGIO1/ZMN1T/setVal": "ЗМН.1 Т",
              "LD0/SetZMN_GGIO1/ZMN1U/setMag/f": "ЗМН.1 U",
              "LD0/SetZMN_GGIO1/ZMN1U2/setMag/f": "ЗМН.1 U2",
              "LD0/SetZMN_GGIO1/ZMN2S1/setVal": "ЗМН.2 S1",
              "LD0/SetZMN_GGIO1/ZMN2S2/setVal": "ЗМН.2 S2",
              "LD0/SetZMN_GGIO1/ZMN2S3/setVal": "ЗМН.2 S3",
              "LD0/SetZMN_GGIO1/ZMN2T/setVal": "ЗМН.2 Т",
              "LD0/SetZMN_GGIO1/ZMN2U/setMag/f": "ЗМН.2 U",
              "LD0/SetZMN_GGIO1/ZMN2U2/setMag/f": "ЗМН.2 U2",
              "LD0/SetZOF_GGIO1/RNMopPhiMCh/setMag/f": "РНМоп Фмч",
              "LD0/SetZOF_GGIO1/ZOF1I2/setMag/f": "ЗОФ.1 I2",
              "LD0/SetZOF_GGIO1/ZOF1K/setMag/f": "ЗОФ.1 K",
              "LD0/SetZOF_GGIO1/ZOF1S1/setVal": "ЗОФ.1 S1",
              "LD0/SetZOF_GGIO1/ZOF1S2/setVal": "ЗОФ.1 S2",
              "LD0/SetZOF_GGIO1/ZOF1T/setVal": "ЗОФ.1 Т",
              "LD0/SetZOF_GGIO1/ZOF2I2/setMag/f": "ЗОФ.2 I2",
              "LD0/SetZOF_GGIO1/ZOF2S1/setVal": "ЗОФ.2 S1",
              "LD0/SetZOF_GGIO1/ZOF2S3/setVal": "ЗОФ.2 S3",
              "LD0/SetZOF_GGIO1/ZOF2Tobr/setVal": "ЗОФ.2 Тобр",
              "LD0/SetZOF_GGIO1/ZOF2Tpr/setVal": "ЗОФ.2 Тпр",
              "LD0/SetZOF_GGIO1/ZOF2U2/setMag/f": "ЗОФ.2 U2",
              "LD0/SetZOZZ_GGIO1/RNMnpPhiMCh/setMag/f": "РНМнп Фмч",
              "LD0/SetZOZZ_GGIO1/RNMnpPhiZone/setMag/f": "РНМнп Фзоны",
              "LD0/SetZOZZ_GGIO1/SNOZZS1/setVal": "СНОЗЗ S1",
              "LD0/SetZOZZ_GGIO1/SNOZZS2/setVal": "СНОЗЗ S2",
              "LD0/SetZOZZ_GGIO1/ZOZZ13I0/setMag/f": "ЗОЗЗ.1 3I0",
              "LD0/SetZOZZ_GGIO1/ZOZZ13U0/setMag/f": "ЗОЗЗ.1 3U0",
              "LD0/SetZOZZ_GGIO1/ZOZZ1S1/setVal": "ЗОЗЗ.1 S1",
              "LD0/SetZOZZ_GGIO1/ZOZZ1S2/setVal": "ЗОЗЗ.1 S2",
              "LD0/SetZOZZ_GGIO1/ZOZZ1T/setVal": "ЗОЗЗ.1 Т",
              "LD0/SetZOZZ_GGIO1/ZOZZ23I0/setMag/f": "ЗОЗЗ.2 3I0",
              "LD0/SetZOZZ_GGIO1/ZOZZ23U0/setMag/f": "ЗОЗЗ.2 3U0",
              "LD0/SetZOZZ_GGIO1/ZOZZ2S1/setVal": "ЗОЗЗ.2 S1",
              "LD0/SetZOZZ_GGIO1/ZOZZ2S2/setVal": "ЗОЗЗ.2 S2",
              "LD0/SetZOZZ_GGIO1/ZOZZ2S3/setVal": "ЗОЗЗ.2 S3",
              "LD0/SetZOZZ_GGIO1/ZOZZ2T/setVal": "ЗОЗЗ.2 Т",
              "LD0/SetZPN_GGIO1/ZPNS1/setVal": "ЗПН S1",
              "LD0/SetZPN_GGIO1/ZPNT/setVal": "ЗПН Т",
              "LD0/SetZPN_GGIO1/ZPNU/setMag/f": "ЗПН U",
              "LD0/SetZPP_GGIO1/ZPPF/setMag/f": "ЗПП F",
              "LD0/SetZPP_GGIO1/ZPPS1/setVal": "ЗПП S1",
              "LD0/SetZPP_GGIO1/ZPPT/setVal": "ЗПП Т",
              "LD0/TN2_TVTR2/Rat/setMag/f": "Ктр Uтн2",
              "LD0/User_GAPC1/Kzavhar/setMag/f": "К зав.хар.",
              "LD0/User_GAPC1/Nzavhar/setVal": "N зав.хар.",
              "LD0/User_GAPC1/POlF1/setMag/f": "ПО< F 1",
              "LD0/User_GAPC1/POlF2/setMag/f": "ПО< F 2",
              "LD0/User_GAPC1/POlImax/setMag/f": "ПО< Iмакс",
              "LD0/User_GAPC1/POlUmax/setMag/f": "ПО< Uмакс",
              "LD0/User_GAPC1/POlUmin1/setMag/f": "ПО< Uмин 1",
              "LD0/User_GAPC1/POlUmin2/setMag/f": "ПО< Uмин 2",
              "LD0/User_GAPC1/POlUmin3/setMag/f": "ПО< Uмин 3",
              "LD0/User_GAPC1/POlUmin4/setMag/f": "ПО< Uмин 4",
              "LD0/User_GAPC1/POlUtn2/setMag/f": "ПО< Uтн2",
              "LD0/User_GAPC1/POm3I0/setMag/f": "ПО> 3I0",
              "LD0/User_GAPC1/POm3I0r/setMag/f": "ПО> 3I0р",
              "LD0/User_GAPC1/POm3U01/setMag/f": "ПО> 3U0 1",
              "LD0/User_GAPC1/POm3U02/setMag/f": "ПО> 3U0 2",
              "LD0/User_GAPC1/POmF1/setMag/f": "ПО> F 1",
              "LD0/User_GAPC1/POmF2/setMag/f": "ПО> F 2",
              "LD0/User_GAPC1/POmI2/setMag/f": "ПО> I2",
              "LD0/User_GAPC1/POmIf1/setMag/f": "ПО> Iф 1",
              "LD0/User_GAPC1/POmIf2/setMag/f": "ПО> Iф 2",
              "LD0/User_GAPC1/POmImax1/setMag/f": "ПО> Iмакс 1",
              "LD0/User_GAPC1/POmImax2/setMag/f": "ПО> Iмакс 2",
              "LD0/User_GAPC1/POmImax3/setMag/f": "ПО> Iмакс 3",
              "LD0/User_GAPC1/POmU21/setMag/f": "ПО> U2 1",
              "LD0/User_GAPC1/POmU22/setMag/f": "ПО> U2 2",
              "LD0/User_GAPC1/POmU23/setMag/f": "ПО> U2 3",
              "LD0/User_GAPC1/POmUmax1/setMag/f": "ПО> Uмакс 1",
              "LD0/User_GAPC1/POmUmax2/setMag/f": "ПО> Uмакс 2",
              "LD0/User_GAPC1/POmUmax3/setMag/f": "ПО> Uмакс 3",
              "LD0/User_GAPC1/POmUmax4/setMag/f": "ПО> Uмакс 4",
              "LD0/User_GAPC1/POmUtn2/setMag/f": "ПО> Uтн2",
              "LD0/User_GAPC1/SA01/setVal": "SA01",
              "LD0/User_GAPC1/SA02/setVal": "SA02",
              "LD0/User_GAPC1/SA03/setVal": "SA03",
              "LD0/User_GAPC1/SA04/setVal": "SA04",
              "LD0/User_GAPC1/SA05/setVal": "SA05",
              "LD0/User_GAPC1/SA06/setVal": "SA06",
              "LD0/User_GAPC1/SA07/setVal": "SA07",
              "LD0/User_GAPC1/SA08/setVal": "SA08",
              "LD0/User_GAPC1/SA09/setVal": "SA09",
              "LD0/User_GAPC1/SA10/setVal": "SA10",
              "LD0/User_GAPC1/SA11/setVal": "SA11",
              "LD0/User_GAPC1/SA12/setVal": "SA12",
              "LD0/User_GAPC1/SA13/setVal": "SA13",
              "LD0/User_GAPC1/SA14/setVal": "SA14",
              "LD0/User_GAPC1/SA15/setVal": "SA15",
              "LD0/User_GAPC1/SA16/setVal": "SA16",
              "LD0/User_GAPC1/SA17/setVal": "SA17",
              "LD0/User_GAPC1/SA18/setVal": "SA18",
              "LD0/User_GAPC1/SA19/setVal": "SA19",
              "LD0/User_GAPC1/SA20/setVal": "SA20",
              "LD0/User_GAPC1/SA21/setVal": "SA21",
              "LD0/User_GAPC1/SA22/setVal": "SA22",
              "LD0/User_GAPC1/SA23/setVal": "SA23",
              "LD0/User_GAPC1/SA24/setVal": "SA24",
              "LD0/User_GAPC1/SA25/setVal": "SA25",
              "LD0/User_GAPC1/TA01/setVal": "TA01",
              "LD0/User_GAPC1/TA02/setVal": "TA02",
              "LD0/User_GAPC1/TA03/setVal": "TA03",
              "LD0/User_GAPC1/TA04/setVal": "TA04",
              "LD0/User_GAPC1/TA05/setVal": "TA05",
              "LD0/User_GAPC1/TA06/setVal": "TA06",
              "LD0/User_GAPC1/TA07/setVal": "TA07",
              "LD0/User_GAPC1/TA08/setVal": "TA08",
              "LD0/User_GAPC1/TA09/setVal": "TA09",
              "LD0/User_GAPC1/TA10/setVal": "TA10",
              "LD0/User_GAPC1/TA11/setVal": "TA11",
              "LD0/User_GAPC1/TA12/setVal": "TA12",
              "LD0/User_GAPC1/TA13/setVal": "TA13",
              "LD0/User_GAPC1/TA14/setVal": "TA14",
              "LD0/User_GAPC1/TA15/setVal": "TA15",
              "LD0/User_GAPC1/TA16/setVal": "TA16",
              "LD0/User_GAPC1/TA17/setVal": "TA17",
              "LD0/User_GAPC1/TA18/setVal": "TA18",
              "LD0/User_GAPC1/TA19/setVal": "TA19",
              "LD0/User_GAPC1/TA20/setVal": "TA20",
              "LD0/User_GAPC1/TL01/setVal": "TL01",
              "LD0/User_GAPC1/TL02/setVal": "TL02",
              "LD0/User_GAPC1/TL03/setVal": "TL03",
              "LD0/CALH1/AlmReset/ctlModel": "АСУ_Квитирование",
              "LD0/PTUF1/Reset/ctlModel": "АСУ_АЧР.1 возвр.",
              "LD0/PTUF2/Reset/ctlModel": "АСУ_АЧР.2 возвр.",
              "LD0/PTUF3/Reset/ctlModel": "АСУ_АЧР.3 возвр.",
              "LD0/PTUV1/Reset/ctlModel": "АСУ_АРСН.1 возвр.",
              "LD0/PTUV2/Reset/ctlModel": "АСУ_АРСН.2 возвр.",
              "LD0/PTUV3/Reset/ctlModel": "АСУ_АРСН.3 возвр.",
              "LD0/Q1_CSWI1/Pos/ctlModel": "850_Cmd_XCBR_pos",
              "LD0/RDRE1/RcdTrg/ctlModel": "АСУ_Осциллограф",
              "LD0/User_GAPC1/SPCSO1/ctlModel": "АСУ_Вход 1",
              "LD0/User_GAPC1/SPCSO2/ctlModel": "АСУ_Вход 2",
              "LD0/User_GAPC1/SPCSO3/ctlModel": "АСУ_Вход 3",
              "LD0/User_GAPC1/SPCSO4/ctlModel": "АСУ_Вход 4",
              "LD0/User_GAPC1/SPCSO5/ctlModel": "АСУ_Вход 5",
              "LD0/User_GAPC1/SPCSO6/ctlModel": "АСУ_Вход 6",
              "LD0/User_GAPC1/SPCSO7/ctlModel": "АСУ_Вход 7",
              "LD0/User_GAPC1/SPCSO8/ctlModel": "АСУ_Вход 8"}
